"""Deep claim extraction for videos 23-32."""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _extract_v1_builders import (
    src, claim, edge, person, incident, technology, concept, document,
    event, program, location, phenomenon
)
from _extract_helpers import write_output


def extend(vid: str, new_entities: list[dict], claims_data: list[tuple]) -> None:
    path = Path(__file__).parent / "entities" / f"{vid}.json"
    existing = json.loads(path.read_text())
    nodes: list[dict] = list(existing["nodes"])
    edges_list: list[dict] = list(existing["edges"])
    ids = {n["id"] for n in nodes}

    def S(t=0, q=""):
        return [src(vid, t, None, q)]

    for e in new_entities:
        if e["id"] not in ids:
            nodes.append(e)
            ids.add(e["id"])

    for slug, t, stmt, asserter, assertability, subs, quote in claims_data:
        cl = claim(slug, stmt, asserter, vid, t, assertability, subs,
                   S(t, quote), quote=quote)
        nodes = [n for n in nodes if n["id"] != cl["id"]]
        ids.discard(cl["id"])
        nodes.append(cl)
        ids.add(cl["id"])
        edges_list.append(edge(asserter, cl["id"], "ASSERTED",
                              S(t, stmt[:200]), 0.95))
        edges_list.append(edge(f"video-{vid}", cl["id"], "REFERENCES",
                              S(t), 0.95))
        for subj in subs:
            if subj != asserter and subj != f"video-{vid}":
                edges_list.append(edge(cl["id"], subj, "REFERENCES",
                                      S(t), 0.85))

    out = {"video_id": vid, "nodes": nodes, "edges": edges_list}
    write_output(out, vid)
    print(f"  {vid}: {len(nodes)} nodes, {len(edges_list)} edges")


def P(slug, label, vid, t, quote, summary, aliases=None, prof="", notability=None):
    return person(slug, label, [src(vid, t, None, quote)],
                  summary=summary, aliases=aliases or [], profession=prof,
                  notability=notability or [])


# ========== VIDEO 23: hBrfe4hFuM0 — James Fox / Varginha 1996 ==========
VID23 = "hBrfe4hFuM0"
entities_23 = [
    P("james-fox", "James Fox", VID23, 11,
      "Documentary filmmaker of 'Moment of Contact' and 'The Phenomenon'",
      "Documentary filmmaker behind 'The Phenomenon' (2020) and 'Moment of Contact' — investigating Varginha 1996 and surrounding witnesses.",
      ["Fox"], "filmmaker",
      ["filmmaker", "investigator"]),
    P("carlos-dusa", "Carlos de Souza", VID23, 29,
      "Brazilian ultralight pilot who witnessed cigar-shaped UFO crash Jan 13 1996",
      "Brazilian ultralight pilot who witnessed a cigar-shaped craft in distress on Jan 13 1996 near São Paulo; traveled to Molini Farm crash site; intimidated by black-suited Portuguese-speaking operatives at gunpoint.",
      ["Carlos Dza"], "pilot",
      ["witness", "pilot", "Varginha"]),
    P("fabio-futado", "Fabio Furtado", VID23, 21,
      "Farmer witness to Varginha 1996 cigar-shaped craft",
      "Brazilian farmer who witnessed the Varginha cigar-shaped UFO in January 1996.",
      ["Futado", "Furtado"], "farmer", ["witness", "Varginha"]),
    P("emma-francis-barwood", "Emma Francis Barwood", VID23, 47,
      "Phoenix City Councilwoman who investigated 1997 Phoenix Lights",
      "Phoenix City Councilwoman; one of the few officials who publicly investigated the 1997 Phoenix Lights incident.",
      ["Barwood"], "politician",
      ["politician", "investigator"]),
    P("richard-dolan", "Richard Dolan", VID23, 55,
      "UFO historian and author of UFOs and the National Security State",
      "American UFO historian; chronicled 'men in black'-style confiscation events and national-security state UAP suppression patterns.",
      ["Dolan"], "historian", ["historian", "author"]),
    incident("1996-varginha-brazil", "Varginha Brazil UFO Crash", "crash_retrieval", "1996-01-13",
        [src(VID23, 19, "Cigar-shaped craft crash near São Paulo with alien beings retrieved")],
        summary="January 13 1996 UFO crash near São Paulo, Brazil. Cigar-shaped craft (~size of school bus) described as intelligent and wounded before crashing. Witnesses include pilot Carlos de Souza. Extensive men-in-black intimidation of witnesses. Alien beings reportedly captured."),
    incident("1997-phoenix-lights", "1997 Phoenix Lights", "mass_sighting", "1997-03-13",
        [src(VID23, 49, "Massive V-shaped/boomerang craft over Phoenix Arizona")],
        summary="March 13 1997 Phoenix Lights mass sighting — massive boomerang/V-shaped craft witnessed by thousands over Phoenix, including the Arizona governor (who later admitted)."),
    document("moment-of-contact", "Moment of Contact", "broadcast",
        [src(VID23, 23, "James Fox's documentary on Varginha 1996")],
        summary="James Fox's Showtime documentary on the Varginha 1996 UFO crash and its witnesses.",
        author="James Fox"),
    concept("men-in-black-confiscation", "Men-in-Black Witness Confiscation Pattern", "politics",
        [src(VID23, 55, "Richard Dolan catalogs repeated pattern across cases")],
        summary="Recurring pattern (documented by Richard Dolan) of unmarked-vehicle, black-suited, well-informed operatives arriving within hours of a UFO sighting to confiscate footage and intimidate witnesses — across Varginha, Phoenix Lights, and many other cases."),
]
claims_23 = [
    ("varginha-cigar-crash-jan13", 29,
     "On January 13 1996 a cigar-shaped craft (size of a school bus) crashed at the Molini Farm near São Paulo Brazil; Carlos de Souza witnessed it descending in distress as he was going up to fly an ultralight.",
     "person-carlos-dusa", "personal_account",
     ["person-carlos-dusa", "incident-1996-varginha-brazil"],
     "He sees an object with a gash in the back. He was like a craft. I'm going down. So it's really early in the morning. A place called the Molini Farm."),
    ("varginha-ammonia-memory-metal", 31,
     "The Varginha crash site emitted a strong ammonia smell; witnesses described debris field bigger than a football field with weightless memory-metal material that reformed after crumpling — mirroring Roswell reports.",
     "person-carlos-dusa", "personal_account",
     ["person-carlos-dusa", "incident-1996-varginha-brazil", "technology-memory-metal",
      "incident-1947-roswell"],
     "Like a debris field bigger than a football field. Smelled ammonia. He picked up one of the pieces and crumple it up really light. Like Roswell people."),
    ("varginha-carlos-men-in-black", 39,
     "Carlos de Souza was intercepted at a gas station by perfectly-aligned black-suited operatives in a plate-less car who recited his entire personal history (name, wife, address, daughter) and threatened him to silence.",
     "person-carlos-dusa", "personal_account",
     ["person-carlos-dusa", "incident-1996-varginha-brazil",
      "concept-men-in-black-confiscation"],
     "An unmarked black car without a license plate. Dressed in black suits, all perfectly aligned. They said your family, address — my entire life story right there. They said if you ever talk about it, we'll hunt you down and kill you."),
    ("varginha-animal-distress", 25,
     "Animals (dogs, farmers' livestock) detected the Varginha craft before humans — made a ruckus at 2-3 AM before the craft was visible — yet the craft itself was absolutely silent.",
     "person-james-fox", "cited_from_document",
     ["person-james-fox", "incident-1996-varginha-brazil"],
     "The animals or the farmers — a ruckus at 2:00 or 3:00 in the morning — was there. It was absolutely silent."),
    ("phoenix-lights-barwood-investigation", 47,
     "Phoenix Councilwoman Emma Francis Barwood was one of the only elected officials who publicly investigated the 1997 Phoenix Lights; the Arizona governor later admitted seeing the craft.",
     "person-james-fox", "cited_from_document",
     ["person-emma-francis-barwood", "incident-1997-phoenix-lights"],
     "Council woman Francis Barwood — one of the few was willing to hey she said 'Let's just investigate.' The governor has now admitted."),
    ("phoenix-lights-footage-confiscation", 51,
     "A Vietnam-vet witness filmed 1997 Phoenix Lights from his rooftop; arranged to share footage with Barwood's office — men in dark suits 'from Emma Barwood's office' arrived next day, took the footage, no copies, Barwood never saw it.",
     "person-james-fox", "cited_from_document",
     ["incident-1997-phoenix-lights", "concept-men-in-black-confiscation",
      "person-emma-francis-barwood"],
     "They said they were from Emma Barwood's office. We're here to pick up the footage. Took the footage and left. I didn't send anybody."),
    ("dolan-mib-systematic-pattern", 55,
     "Richard Dolan documents the men-in-black confiscation pattern repeating systematically across Varginha, Phoenix Lights, and other cases — not individual anomalies but operational counterintelligence.",
     "person-james-fox", "cited_from_document",
     ["person-richard-dolan", "concept-men-in-black-confiscation"],
     "Richard Dolan — happening time and time and time again."),
]

# ========== VIDEO 24: KhmUixSXxDo — Alex Jones ==========
VID24 = "KhmUixSXxDo"
entities_24 = [
    P("alex-jones", "Alex Jones", VID24, 73,
      "InfoWars founder, conspiracy broadcaster",
      "Founder of InfoWars; controversial American broadcaster. Started as populist-libertarian anti-war commentator (Richard Linklater's 'Waking Life' speech 2001); later evolved into lightning rod for mainstream-conspiracy discourse.",
      ["Jones"], "broadcaster",
      ["broadcaster", "journalist", "controversial"]),
    P("richard-linklater", "Richard Linklater", VID24, 77,
      "American filmmaker; Waking Life director",
      "American filmmaker who featured Alex Jones in 'Waking Life' (2001).",
      ["Linklater"], "filmmaker", ["filmmaker"]),
    P("rene-girard", "René Girard", VID24, 113,
      "French philosopher of mimetic theory and scapegoat mechanism",
      "French philosopher whose scapegoat-mechanism theory Jesse invokes to frame Alex Jones' role in public discourse as sacrificial archetype.",
      ["Girard", "Gerard"], "philosopher", ["philosopher", "historical"]),
    event("bohemian-grove-infiltration-2000", "Alex Jones Bohemian Grove Infiltration", "meeting", "2000-07-15",
        [src(VID24, 93, "Jones snuck into California secret society in 2000")],
        summary="July 2000: Alex Jones infiltrated the Bohemian Grove (Northern California elite secret society) and filmed the 'Cremation of Care' pagan midsummer ritual."),
    concept("cremation-of-care", "Cremation of Care Ritual", "metaphysics",
        [src(VID24, 93, "Pagan midsummer scapegoating ritual at Bohemian Grove")],
        summary="Pagan midsummer scapegoating ritual performed at Bohemian Grove; Jones describes fusion of Moloch worship, Faustian occultism, and druidic occultism among ~1,000 elite American male attendees."),
    location("bohemian-grove", "Bohemian Grove", "observation_site",
        [src(VID24, 91, "Northern California secret society retreat")],
        country="US", state="California"),
]
claims_24 = [
    ("jones-bohemian-grove-cremation-of-care", 93,
     "In July 2000 Alex Jones infiltrated the Bohemian Grove and witnessed the 'Cremation of Care' ritual — ~1,000 men in an extended pagan ceremony that Jones frames as a fusion of Moloch worship with Faustian occultism and druidic occultism.",
     "person-alex-jones", "personal_account",
     ["person-alex-jones", "event-bohemian-grove-infiltration-2000",
      "concept-cremation-of-care", "location-bohemian-grove"],
     "When you snuck into the Bohemian Grove, you looked at this crazy ritual called the cremation of care. I was in the crowd with the men and they were taking this extremely seriously. It was a fusion of Moloch worship, Faustian occultism and druidic occultism."),
    ("jones-as-scapegoat-girard", 113,
     "Jesse frames Alex Jones' public trajectory through René Girard's scapegoat-mechanism theory: Jones was harvested as the archetype of the marginalized populist dissident — demonized as a pressure valve.",
     "person-jesse-michels", "speculation",
     ["person-alex-jones", "person-rene-girard"],
     "There's this philosopher I like named René Girard. He has this theory that there are scapegoats that can sometimes be constructed as pressure valve releases. I was used as the archetype of let's just ban Alex Jones."),
    ("jones-qanon-disinfo-recognition", 109,
     "Jones states he recognized QAnon as a disinformation operation early; broke with his own audience over it ('I'm not being set up this time').",
     "person-alex-jones", "personal_account",
     ["person-alex-jones"],
     "When I saw QAnon come along, I was like 'I've been set up repeatedly. I'm not being set up this time. This is BS.' A lot of my listeners got mad at me."),
    ("jones-waking-life-philosopher", 117,
     "Jones appeared in Richard Linklater's 'Waking Life' (2001) giving what Jesse calls 'the best speech ever' on human empowerment — foreshadowing his origin as a philosopher-turned-political-figure.",
     "person-alex-jones", "cited_from_document",
     ["person-alex-jones", "person-richard-linklater"],
     "My first exposure to you was watching Richard Linklater's Waking Life. It's like the best speech ever. It's all about human empowerment. You were a philosopher — that got forced into politics."),
]

# ========== VIDEO 25: areO7Mej44E — Steven Greer ==========
VID25 = "areO7Mej44E"
entities_25 = [
    P("steven-greer-full", "Steven Greer", VID25, 143,
      "Medical doctor turned UFO disclosure advocate; Disclosure Project",
      "American medical doctor; founded Disclosure Project (1993) and CSETI; has gathered more first-hand UFO witnesses than anyone. Controversial figure in UFO community.",
      ["Greer", "Dr. Greer", "Stephen Greer"], "medical doctor",
      ["advocate", "researcher", "disclosure", "controversial"]),
    P("john-warner-iv", "John Warner IV", VID25, 175,
      "Grandson of Paul Mellon who admitted family fascism/Nazi-UFO history to Greer",
      "Grandson of Paul Mellon; son of Senator John Warner III. In conversation with Steven Greer, acknowledged family history of fascism support and grandfather Paul Mellon's retrieval of a Nazi flying disc.",
      ["Warner"], "", ["witness", "historical"]),
    P("paul-mellon", "Paul Mellon", VID25, 175,
      "Billionaire industrialist; retrieved Nazi disc post-WWII",
      "American billionaire industrialist; OSS WWII; per grandson John Warner IV, retrieved a Nazi electrogravitic flying disc from Germany in 1945.",
      ["Mellon"], "industrialist",
      ["intelligence", "historical", "financier"]),
    P("richard-foch", "Richard Foch", VID25, 185,
      "Naval Research Labs top scientist; confirmed gravity control mastered Oct 1954",
      "Top scientist at US Naval Research Labs who privately revealed to Greer he had seen vault documents confirming gravity control was mastered in October 1954. Deceased.",
      ["Foch"], "scientist", ["scientist", "Navy", "whistleblower"]),
    P("prescott-bush", "Prescott Bush", VID25, 179,
      "Senator; George H.W. Bush's father; alleged Hitler supporter",
      "US Senator from Connecticut; father of George H.W. Bush; cited by Greer (per Warner IV) as among the financial-elite Americans supporting fascism via Union Bank / Brown Brothers Harriman.",
      ["Bush"], "senator / financier", ["historical", "senator"]),
    P("jackie-gleason", "Jackie Gleason", VID25, 171,
      "Entertainer allegedly shown UFO bodies by Richard Nixon",
      "American entertainer/comedian; per long-standing UFO lore and Greer's sources, shown UFO bodies by President Nixon at Homestead AFB.",
      ["Gleason"], "entertainer", ["witness", "historical"]),
    document("disclosure-project-briefing-2025", "Disclosure Project Briefing Document 2025", "report",
        [src(VID25, 155, "Briefing prepared for new US President post-2024 election")],
        summary="Steven Greer's Disclosure Project 2025 briefing document prepared for the incoming US President with 90%+ of relevant content; redacted and released publicly."),
    program("project-starlight", "Project Starlight (Disclosure Project precursor)",
        [src(VID25, 171, "Mid-1990s Greer initiative; precursor to Disclosure Project")],
        summary="Mid-1990s effort led by Greer that became the public Disclosure Project launched at the National Press Club in 2001.",
        acronym="Starlight"),
]
claims_25 = [
    ("greer-paul-mellon-nazi-disc-1945", 181,
     "Per John Warner IV's conversation with Greer: Paul Mellon personally retrieved a Nazi electrogravitic flying disc (not a ramjet) from Germany in 1945; it was unstable.",
     "person-steven-greer-full", "hearsay",
     ["person-steven-greer-full", "person-john-warner-iv", "person-paul-mellon",
      "program-operation-paperclip"],
     "I walked in, he goes well my whole family are fascists. Paul Mellon admitted going over and getting a Nazi disc. It was actually electrogravidic."),
    ("foch-gravity-mastered-october-1954", 185,
     "Naval Research Labs top scientist Richard Foch confirmed to Greer he had been in the vault and seen documents dated October 1954 for the date the US mastered gravity control.",
     "person-steven-greer-full", "hearsay",
     ["person-steven-greer-full", "person-richard-foch", "concept-antigravity"],
     "Rick had been in the vault and saw the documents for the date we mastered gravity control and it was October 1954."),
    ("greer-911-as-ufo-disclosure-diversion", 173,
     "Greer argues that the Disclosure Project's 2001 National Press Club event (seen by 800M people) was about to break UAP wide open — and 9/11 happened months later 'as a direct consequence' diversion.",
     "person-steven-greer-full", "speculation",
     ["person-steven-greer-full", "program-project-starlight"],
     "When we kicked off the whole disclosure project effort — at the National Press Club that had 800 million people see it. And then 9/11 happened a few months later as a direct consequence."),
    ("greer-jfk-killed-over-ufo", 165,
     "Greer states (citing sources with 'actionable intelligence') that JFK was killed over the UAP issue — specifically over the constellation of programs attached to the 'Gaps' science-and-technology branch.",
     "person-steven-greer-full", "hearsay",
     ["person-steven-greer-full", "person-jfk"],
     "Jack Kennedy was killed over this issue and the constellation of programs attached to Gaps and particularly the science and technology branch of it."),
    ("greer-alien-threat-is-psyop", 167,
     "Greer asserts there is an active government effort to spin UAP as an 'alien threat' in order to lay foundation for a totalitarian superstate — calling this a 'total hoax and nonsense' and a CIA-authored script.",
     "person-steven-greer-full", "on_record_statement",
     ["person-steven-greer-full", "concept-disclosure"],
     "They want people to go out publicly who will spin the subject in the direction of it being an alien threat for the purpose of a totalitarian superstate uniting the world against aliens, which is a total hoax and nonsense. That whole script was like out of CIA central scripting casting."),
    ("greer-had-abduction-squad-confessions", 141,
     "Greer states on camera he met people who worked on the human-operated 'abduction squad' — made to impersonate aliens — who now feel terrible about their past actions.",
     "person-steven-greer-full", "hearsay",
     ["person-steven-greer-full", "concept-nhi"],
     "I had guys come forward who had actually been on the abduction squad made to look like aliens. And they feel terrible later in life."),
    ("greer-disclosure-briefing-2025", 155,
     "Greer prepared a redacted Disclosure Project briefing document for the new US administration with 90%+ of the content the President sees — now publicly released.",
     "person-steven-greer-full", "personal_account",
     ["person-steven-greer-full", "document-disclosure-project-briefing-2025"],
     "You'll have 90 plus% of what the new president has. The disclosure project briefing document 2025."),
]

# ========== VIDEO 26: TH10mD9hQas — Solo Jesse recap "How I Know Grusch Not Lying" ==========
VID26 = "TH10mD9hQas"
entities_26 = [
    P("edward-condon-batch26", "Edward Condon (Blue Book debunker)", VID26, 229,
      "Quantum physicist who led Condon Committee UFO investigation",
      "Quantum physicist Max Born-educated; helped Oppenheimer select Los Alamos; drafted McMahon Atomic Energy Act 1946; lost clearance over communist sympathies; suddenly restored clearance in 1966 and placed on Condon Committee which dealt death blow to UFO research. Possible blackmail by FBI's Guy Hottel.",
      ["Condon"], "physicist", ["skeptic", "debunker", "Manhattan Project"]),
    P("guy-hottel", "Guy Hottel", VID26, 237,
      "FBI field agent famous for 1952 'Hottel memo' on UFO crash + dead aliens",
      "FBI field agent who authored the 1952 Hottel memo (the most-read document on the FBI website) describing an Air Force officer's account of a crashed UFO with alien crew. Building field reports dossier on Condon during his 1950s clearance investigation.",
      ["Hottel", "Hoddle"], "FBI agent", ["FBI", "historical", "counterintelligence"]),
    P("max-born-physicist", "Max Born", VID26, 229,
      "German physicist; mentor to Oppenheimer and Condon at Göttingen",
      "German-British physicist; Nobel laureate; quantum mechanics pioneer; mentor of Oppenheimer and Condon at Göttingen in the 1920s.",
      ["Born"], "physicist", ["physicist", "historical", "Nobel"]),
    document("hottel-memo-1952", "Hottel Memo (1952)", "memo",
        [src(VID26, 237, "FBI memo describing 3 flying saucers recovered in New Mexico")],
        summary="March 22 1952 memo from FBI agent Guy Hottel to Director Hoover describing three flying saucers recovered in New Mexico with occupants three feet tall. Most-read FOIA document on FBI.gov.",
        author="Guy Hottel", year=1952),
    concept("manhattan-project-clearance-system", "Manhattan Project Clearance System", "politics",
        [src(VID26, 223, "UAP clearances may route through DOE not executive branch")],
        summary="Per Jacques Vallee and Grusch: UFO-program clearance system routes through the Manhattan Project → Atomic Energy Commission → Department of Energy lineage rather than through the Pentagon / Executive Branch — explaining why above-top-secret cleared personnel at the Pentagon have never heard of the programs."),
    concept("condon-blackmail-hypothesis", "Condon Blackmail Hypothesis", "politics",
        [src(VID26, 237, "FBI blackmail forcing Condon into UFO debunker role")],
        summary="Jesse's hypothesis: Guy Hottel's FBI field-report dossier on Condon (built during his 1950s clearance investigation) was used to blackmail/compel Condon into becoming the public-facing UFO debunker on the Condon Committee after his clearance was 'mysteriously' restored in 1966."),
]
claims_26 = [
    ("recap-atomic-energy-act-ufo-overlay", 221,
     "Grusch's claim recap: the 1954 Atomic Energy Act's definition of 'special nuclear material' ('any material that releases radiological energy') was deliberately worded to cover retrieved UFO crash material under nuclear secrecy.",
     "person-jesse-michels", "cited_from_document",
     ["person-david-grusch", "document-atomic-energy-act-1954",
      "concept-crash-retrieval"],
     "If you actually read the Atomic Energy Act, if something is not a nuke but it has radiological energy coming off it — alpha beta decay whatever — same secrecy."),
    ("recap-vallee-doe-clearance-system", 223,
     "Vallee asserts the Manhattan Project → Atomic Energy Commission → DOE clearance lineage governs UFO secrecy — not the Pentagon/Executive Branch — which is why Pentagon above-top-secret personnel have never heard of these programs.",
     "person-jesse-michels", "cited_from_document",
     ["person-jacques-vallee", "concept-manhattan-project-clearance-system",
      "program-manhattan-project"],
     "Jacques Vallee also says that the DOE and the Manhattan Project clearance system is the most applicable to UFOs — not the clearances that roll up to the Executive Branch."),
    ("recap-hottel-condon-blackmail", 237,
     "Jesse hypothesizes that FBI agent Guy Hottel (author of the 1952 Hottel UFO memo) built a field-report dossier on Condon during the 1950s communist-sympathy investigation, then used it to blackmail Condon into becoming the UFO debunker.",
     "person-jesse-michels", "speculation",
     ["person-edward-condon-batch26", "person-guy-hottel", "document-hottel-memo-1952",
      "concept-condon-blackmail-hypothesis"],
     "A dossier of field reports was being created on him in the background by an FBI field agent named Guy Hottel. Hottel definitely knew about UFOs. Was he just building blackmail on Condon and forcing him into becoming a UFO debunker?"),
    ("recap-condon-clearance-restored-1966", 235,
     "Condon mysteriously had his clearance restored in 1966 — immediately placed on the panel that dealt the death blow to academic UFO research.",
     "person-jesse-michels", "cited_from_document",
     ["person-edward-condon-batch26", "event-1966-condon-committee"],
     "Randomly he pops back up in 1966 and his clearance is mysteriously restored. He's then placed on a panel which deals a death blow to UFO research."),
    ("recap-townsend-brown-navy-1942", 241,
     "In 1942 the US Navy fired Townsend Brown without cause despite strong performance; two weeks later he appears at Martin Vega Corporation — one year before Skunkworks was founded.",
     "person-jesse-michels", "cited_from_document",
     ["person-townsend-brown", "organization-us-navy", "organization-martin-corporation",
      "organization-skunkworks"],
     "In 1942 the Navy fires him without cause and mysteriously he shows up at Martin Vega Corporation a year before Skunkworks is formed."),
    ("recap-lockheed-grusch-reply-revealing", 243,
     "Lockheed Skunkworks' on-record response to Grusch's testimony was 'questions about UAPs are best answered by the federal government' — NOT a denial, which Jesse argues is telling.",
     "person-jesse-michels", "cited_from_document",
     ["organization-skunkworks", "person-david-grusch"],
     "Their response to Grusch's testimony was pretty telling — they said questions about UAPs are best answered by the federal government. That's not a flat-out rejection of the premise that they might have UFOs in their possession."),
]

# ========== VIDEO 27: CiQTBOQ1dTg — Tim Alberino ==========
VID27 = "CiQTBOQ1dTg"
entities_27 = [
    P("tim-alberino", "Tim Alberino", VID27, 281,
      "Researcher on Nephilim, ancient giants, Book of Enoch",
      "American researcher and author focused on the Nephilim / Anakim narrative of ancient giants; Kandahar giant investigator; deep scholar of Book of Enoch and Hebrew antediluvian cosmology.",
      ["Alberino"], "researcher / author",
      ["researcher", "author", "biblical-scholar"]),
    document("book-of-enoch", "Book of Enoch", "book",
        [src(VID27, 301, "Foundational Hebrew antediluvian cosmological text")],
        summary="Non-canonical Hebrew text attributed to Enoch; provides foundation for Hebrew cosmology of the antediluvian world; describes 'watchers' (extraterrestrial beings) who mated with humans producing the Nephilim giants.",
        author="Enoch (attributed)"),
    document("epic-of-gilgamesh", "Epic of Gilgamesh", "book",
        [src(VID27, 309, "Mesopotamian epic with giant protagonist")],
        summary="Ancient Mesopotamian epic; Gilgamesh himself is described as a giant. Parallels Hebrew Nephilim tradition with the Anunnakic/Sumerian account of divine-human hybrid beings."),
    concept("watchers-nephilim", "The Watchers & Nephilim", "metaphysics",
        [src(VID27, 271, "Extraterrestrial beings who mated with humans producing giants")],
        summary="Hebrew antediluvian tradition of 'watchers' — extraterrestrial entities who descended, mated with human women, and produced the Nephilim race of hybrid demigod giants. Paralleled across pagan traditions (Greek titans, Mesopotamian Anunnaki, Egyptian gods)."),
    incident("kandahar-giant", "Kandahar Giant Recovery", "crash_retrieval", "2002-01-01",
        [src(VID27, 287, "US cargo pilot witnessed 12-ft red-haired six-fingered giant")],
        summary="Tim Alberino's investigation: US Air Force cargo pilot witnessed a 12-ft tall, 1,100-lb, red-haired, pale-skinned being with six fingers on each hand and six toes on each foot being transported on an air cargo pallet in Afghanistan (classified operation)."),
    concept("sidonia-mars-ruins", "Sidonia (Mars) Ruins", "metaphysics",
        [src(VID27, 275, "Alleged ancient civilization ruins in Sidonia region of Mars")],
        summary="Per Alberino: NHI-era civilizational ruins on Mars in the Sidonia region. Per ancient traditions, the gods descended from Mars."),
]
claims_27 = [
    ("alberino-kandahar-giant", 287,
     "Per Alberino: A US cargo pilot on classified missions witnessed a 12-ft tall, 1,100-lb, six-fingered giant being transported on an air-cargo pallet in Kandahar — hair red, skin pale, 'solid as a rock', never-speak-about-it order.",
     "person-tim-alberino", "cited_from_document",
     ["person-tim-alberino", "incident-kandahar-giant"],
     "He sees a forklift bringing over an air cargo pallet. The hair of this being was red. The skin was pale. It had six fingers on each hand and six toes on each foot. Let's say it was 12 feet tall. The whole thing weighed 1,100 lb."),
    ("alberino-watchers-nephilim", 271,
     "Alberino argues the Book of Enoch documents 'watchers' — extraterrestrial entities who mated with humans producing the Nephilim hybrid race — and this archetype is preserved across Hebrew, Mesopotamian, Greek, Roman, and Egyptian traditions.",
     "person-tim-alberino", "on_record_statement",
     ["person-tim-alberino", "document-book-of-enoch", "concept-watchers-nephilim"],
     "So we have these watchers that came down. They were extraterrestrial. They mated with man. They created Nephilim. These traditions are ubiquitous across the earth."),
    ("alberino-sidonia-mars-ruins", 275,
     "Alberino points to alleged ancient civilization ruins in the Sidonia region of Mars as material evidence corroborating ancient traditions of the gods descending from Mars.",
     "person-tim-alberino", "speculation",
     ["person-tim-alberino", "concept-sidonia-mars-ruins"],
     "There are ruins of an ancient civilization on the planet Mars, specifically in the region of Sidonia. The ancients believed that the gods descended from Mars."),
    ("gilgamesh-giant-parallel", 309,
     "Alberino notes Gilgamesh himself is described as a giant in the Mesopotamian epic, paralleling the Hebrew Nephilim tradition and suggesting a common antediluvian memory of divine-human hybrid beings.",
     "person-tim-alberino", "cited_from_document",
     ["person-tim-alberino", "document-epic-of-gilgamesh", "concept-watchers-nephilim"],
     "In the biblical account and the ancient Mesopotamian account, the epic of Gilgamesh. Gilgamesh himself was a giant."),
    ("alberino-golden-age-zep-tepi", 309,
     "Per Alberino: in Egyptian tradition the antediluvian era is 'Zep Tepi' — a golden age when gods co-mingled with mankind and procreated with human women producing hybrid demigods.",
     "person-tim-alberino", "cited_from_document",
     ["person-tim-alberino", "concept-watchers-nephilim"],
     "In the pagan world, this was known as the golden age or Zep Tepi to the ancient Egyptians. It was a time when the gods co-mingled with mankind. Literally, they procreated with human women."),
    ("alberino-enoch-greatest-preflood-patriarch", 311,
     "Alberino notes Enoch is described as the greatest pre-flood patriarch yet canonical Bible says very little about him — extensive Enochian content exists only in extra-canonical Book of Enoch.",
     "person-tim-alberino", "personal_account",
     ["person-tim-alberino", "document-book-of-enoch"],
     "Among the Jews, there was no greater prophet and scribe than Enoch. The Bible says very little about Enoch — 'walked with God for 365 years and then God took him' — and that's pretty much all."),
]

# ========== VIDEO 28: G7Ns4Aq1tVc — Nick Cook (extends video 10) ==========
VID28 = "G7Ns4Aq1tVc"
entities_28 = [
    document("hunt-for-zero-point", "The Hunt for Zero Point", "book",
        [src(VID28, 337, "Nick Cook's investigative book on aerospace antigravity research")],
        summary="Nick Cook's comprehensive investigation into aerospace companies' hidden antigravity research programs. Documents Skunk Works, Nazi programs under Hans Kammler, and Chinese researcher Ning Li.",
        author="Nick Cook"),
    P("george-s-trimble", "George S. Trimble", VID28, 331,
      "VP of Martin Corporation RIAS, antigravity researcher",
      "Vice President of Martin Corporation's Research Institute for Advanced Study (RIAS); stated in 1956 that antigravity could be achieved 'in about the time it took to build the first atom bomb.' Later refused to speak about it — 'sounded scared' per his Lockheed PR contact.",
      ["Trimble"], "aerospace executive",
      ["aerospace", "antigravity", "historical"]),
    P("bill-sweetman", "Bill Sweetman", VID28, 341,
      "Nick Cook's journalistic collaborator; black-program investigator",
      "Aviation journalist and Nick Cook's 'Sherlock Holmes'; uncovered circumstantial evidence of rumored Mach-5 Lockheed Aurora aircraft.",
      ["Sweetman"], "journalist", ["journalist", "investigator"]),
    P("ning-li", "Ning Li", VID28, 347,
      "Chinese-American physicist; DoD-funded antigravity researcher who vanished",
      "Chinese-American physicist at University of Alabama Huntsville; received DoD grant for anomalous antigravity research; went off-grid/disappeared within a year of her results.",
      ["Li"], "physicist", ["scientist", "missing"]),
    P("hans-kammler", "Hans Kammler", VID28, 345,
      "SS officer overseeing Nazi antigravity programs",
      "Nazi SS officer who oversaw secret German antigravity programs during WWII; resources scavenged for tech by the US and Russia at war's end.",
      ["Kammler"], "military officer", ["Nazi", "historical"]),
    P("victor-schauberger", "Victor Schauberger", VID28, 347,
      "Austrian inventor; anomalous vortex-propulsion research",
      "Austrian inventor who reported anomalous vortex-based propulsion effects; cited in Cook's Hunt for Zero Point.",
      ["Schauberger", "shurger"], "inventor", ["inventor", "historical"]),
    P("john-hutchison", "John Hutchison", VID28, 347,
      "Canadian inventor of the 'Hutchison Effect' anomalous phenomena",
      "Canadian inventor documented by Cook; reported anomalous levitation and material-fusion effects ('Hutchison Effect') using high-voltage fields.",
      ["Hutchison"], "inventor", ["inventor"]),
    P("eugene-podkletnov", "Eugene Podkletnov", VID28, 347,
      "Russian physicist claiming gravitational shielding with spinning superconductors",
      "Russian physicist whose experiments with spinning superconductors reportedly demonstrated gravitational-shielding effects; cited by Cook.",
      ["Podkletnov", "Petna"], "physicist", ["scientist", "antigravity"]),
    P("hans-lear", "Hans Lear (Jan's Defense Weekly article anonymous sender)", VID28, 329,
      "Anonymous source who mailed 1956 article to Nick Cook in 1994",
      "Anonymous source who in 1994 mailed Nick Cook the 1956 'G Engines Are Coming' article at Jan's Defense Weekly — initiating Cook's antigravity investigation.",
      [], "", ["anonymous-source"]),
    document("g-engines-are-coming-1956", "G Engines Are Coming (1956 article)", "paper",
        [src(VID28, 331, "1956 article listing aerospace companies confident in antigravity")],
        summary="1956 magazine article titled 'The G Engines Are Coming' listing top aerospace companies (Lear, Convair, Bell, Martin Corporation) expressing extreme confidence in antigravity aircraft development. Anonymously mailed to Nick Cook in 1994, initiating his Hunt for Zero Point investigation.",
        year=1956),
    technology("lockheed-aurora", "Lockheed Aurora (Mach 5 aircraft)", "craft",
        [src(VID28, 341, "Rumored Mach-5 Lockheed reconnaissance aircraft")],
        summary="Long-rumored classified Mach-5 Lockheed aircraft; Bill Sweetman and Nick Cook uncovered circumstantial evidence supporting its existence."),
]
claims_28 = [
    ("cook-1956-g-engines-article", 331,
     "In 1994 Nick Cook received an anonymously-mailed photocopy of a 1956 magazine article listing top aerospace companies (Lear, Convair, Bell, Martin) confidently predicting antigravity aircraft development — triggering Hunt for Zero Point.",
     "person-nick-cook", "personal_account",
     ["person-nick-cook", "person-george-s-trimble", "document-g-engines-are-coming-1956",
      "organization-martin-corporation"],
     "Someone has placed a photo copy of a strange magazine article from 1956 on his desk. Titled 'The G Engines Are Coming' and it lists the top aerospace companies of the day, Lear, Convair, Bell, the Martin Corporation, all expressing extreme confidence in being able to develop anti-gravity aircraft within the next several years."),
    ("trimble-sounded-scared", 335,
     "Per Cook's Lockheed PR contact in the 1990s: George Trimble initially agreed to an interview, then a few days later refused and 'sounded scared' — 'he doesn't want to speak to me and he doesn't want to speak to you, not now, not ever.'",
     "person-nick-cook", "personal_account",
     ["person-nick-cook", "person-george-s-trimble"],
     "He doesn't want to speak to me and he doesn't want to speak to you, not now, not ever. I don't mind telling you that he sounded scared."),
    ("cook-hans-kammler-ss-antigravity", 345,
     "Cook traces Nazi Germany's antigravity programs under SS officer Hans Kammler; these programs were scavenged at war's end by both the Americans and the Russians for their most valuable technology.",
     "person-nick-cook", "cited_from_document",
     ["person-nick-cook", "person-hans-kammler", "document-hunt-for-zero-point"],
     "Nazi Germany which had its own reported anti-gravity programs under SS officer Hans Kammler. Programs that were scavenged for their most valuable technology by the Americans and the Russians at the end of World War II."),
    ("cook-ning-li-disappeared", 347,
     "Cook interviewed Ning Li — Chinese-American physicist at University of Alabama Huntsville — who received a DoD grant for anomalous antigravity results; she went off-grid within ~1 year, 'nobody knew what happened to her.'",
     "person-nick-cook", "personal_account",
     ["person-nick-cook", "person-ning-li"],
     "Ning Li the mysterious Chinese American physicist who was awarded a DoD grant for her anomalous anti-gravity research results. She just disappeared and no one knew what happened to her."),
    ("cook-we-have-tech-to-take-et-home", 343,
     "Cook concluded his public talks with a slide of a black disc flying off to outer space and the line: 'we now have the technology to take ET home.'",
     "person-nick-cook", "on_record_statement",
     ["person-nick-cook", "document-hunt-for-zero-point"],
     "He ended his talk with a slide of a black disc zipping off into outer space and he ended it with these words: we now have the technology to take ET home."),
    ("cook-mind-over-matter-aerospace", 349,
     "Cook explores aerospace companies' longstanding interest in 'mind over matter' effects and parapsychology — not as fringe but as strategic R&D any advantage must be pursued.",
     "person-nick-cook", "on_record_statement",
     ["person-nick-cook", "concept-stigma-weaponization"],
     "Is there a through line with aerospace and like this interest in mind over matter? These companies look at anything they can that can confer possible advantage."),
]

# ========== VIDEO 29: 2ttdlCa5ZCI — Gary McKinnon ==========
VID29 = "2ttdlCa5ZCI"
entities_29 = [
    P("gary-mckinnon", "Gary McKinnon", VID29, 403,
      "British hacker of 'biggest military computer hack of all time'",
      "British hacker; hacked US Army, Navy, Air Force, DoD, and NASA in 2001-2002 while seeking UFO evidence; faced 70-year US extradition threat (still on pole red list). Autistic; discovered photos of non-terrestrial craft and spreadsheets of 'non-terrestrial officers'.",
      ["McKinnon"], "hacker",
      ["witness", "hacker", "UK"]),
    concept("non-terrestrial-officers", "Non-Terrestrial Officers (NASA spreadsheet)", "politics",
        [src(VID29, 417, "Spreadsheet found on US military servers titled 'non-terrestrial officers'")],
        summary="Spreadsheet title discovered by Gary McKinnon on US DoD / NASA servers; listed names and ranks of purported 'non-terrestrial officers' — i.e., personnel whose assignment was not on Earth."),
    incident("mckinnon-hack-2001-2002", "Gary McKinnon US DoD/NASA Hack", "other", "2001-01-01",
        [src(VID29, 397, "2001-2002 lone hacker infiltration of US military networks")],
        summary="2001-2002 penetration of US DoD, Army, Navy, Air Force, and NASA computer systems from McKinnon's UK bedroom over dial-up — Pentagon's own description: 'the biggest military computer hack of all time.'"),
]
claims_29 = [
    ("mckinnon-hemisphere-cigar-craft", 421,
     "While downloading a slow image file at 4 AM McKinnon witnessed on his screen a black-space hemisphere (a planet) with a silvery cigar-shaped object alongside — mid-image, someone remote-connected and cut him off.",
     "person-gary-mckinnon", "personal_account",
     ["person-gary-mckinnon", "incident-mckinnon-hack-2001-2002"],
     "Slowly a hemisphere started appearing and I'm thinking that's a planet. What the hell? And then suddenly there's a big straight kind of silvery line, cigar-shaped object. I see the mouse move and someone else is at the computer themselves. They right clicked, disconnect, and boom, that was it."),
    ("mckinnon-non-terrestrial-officers", 417,
     "McKinnon found a spreadsheet titled 'non-terrestrial officers' — purporting to list names and ranks of personnel not on Earth.",
     "person-gary-mckinnon", "personal_account",
     ["person-gary-mckinnon", "concept-non-terrestrial-officers",
      "incident-mckinnon-hack-2001-2002"],
     "This spreadsheet was titled non-terrestrial officers, so not on the Earth. And that was incredible."),
    ("mckinnon-70-year-prosecution-threat", 409,
     "The US sought to extradite McKinnon for prosecution carrying up to 70 years prison; UK refused extradition. McKinnon remains on the Interpol 'red list' — cannot enter the US.",
     "person-gary-mckinnon", "on_record_statement",
     ["person-gary-mckinnon", "incident-mckinnon-hack-2001-2002"],
     "They wanted to put you in prison for 70 years. I'm on the Interpol red list."),
    ("mckinnon-heel-holes-incident", 429,
     "After the hacking period, McKinnon was woken by sharp pain — found two perfectly circular holes in his left heel — an unexplained physical mark he attributes to the same class of phenomenon he was investigating.",
     "person-gary-mckinnon", "personal_account",
     ["person-gary-mckinnon"],
     "I was suddenly woken up by a really sharp pain that immediately I just went in my left heel. There were two perfectly circular holes."),
    ("mckinnon-low-tech-dialup-accidental-entry", 421,
     "McKinnon infiltrated the US DoD/NASA with nothing more than a 56K dial-up connection from his bedroom in a dressing gown at 4 AM — 'normal guy interested in UFOs with some IT skills.'",
     "person-gary-mckinnon", "personal_account",
     ["person-gary-mckinnon", "incident-mckinnon-hack-2001-2002"],
     "I was in my dressing gown up till like 4 in the morning, smoking weed, drinking beer. I was on a 56k dialup. Nothing genius level."),
]

# ========== VIDEO 30: y_8IKKcTntQ — Skywatcher ==========
VID30 = "y_8IKKcTntQ"
entities_30 = [
    P("james-valor", "James Valor", VID30, 467,
      "Skywatcher lead operations; retired USAF sergeant major",
      "Retired US Army sergeant major (23 years government service, 2020 retirement); lead operations of Skywatcher UAP detection startup; worked with Jake Barber and Ross Coulthart.",
      ["Valor"], "military veteran / entrepreneur",
      ["military", "entrepreneur"]),
    P("mr-k-skywatcher", "Mr. K (Skywatcher physicist)", VID30, 481,
      "Skywatcher pioneer; physicist working on jet engines and hot rods",
      "Anonymous Skywatcher co-pioneer; physicist who builds jet engines, flamethrowers, and hot rods; first discovered the UAPs over their 2021 war-game location and the 'dog whistle' mechanism.",
      [], "physicist / engineer", ["scientist", "anonymous"]),
    P("mr-d-skywatcher", "Mr. D (Skywatcher signals)", VID30, 485,
      "Skywatcher pioneer; signals-detection discovery",
      "Anonymous Skywatcher co-pioneer; discovered how to detect UAP craft signals via direction-finding and cueing optical cameras to locate them.",
      [], "signals engineer", ["scientist", "anonymous"]),
    concept("uap-dog-whistle", "UAP Dog Whistle", "technology",
        [src(VID30, 457, "Skywatcher technology that reliably summons UAPs")],
        summary="Skywatcher's central technology: a signal emission that reliably attracts UAP presence at their location; 'after we turn on the dog whistle, UAPs literally come to us day after day.' Origin discovered by Skywatcher co-pioneer Mr. K."),
    concept("nine-uap-classes", "Skywatcher UAP Taxonomy (9 Classes)", "physics",
        [src(VID30, 471, "Skywatcher's proposed 9-class UAP taxonomy")],
        summary="Skywatcher's proposed 9-class UAP taxonomy spanning characteristics like shimmer, tumble, spin, apparent-alive-flight, black-body, vapor-sheath, and metallic-glinty morphologies."),
    technology("class-one-tetrahedron", "Class-1 Tetrahedron UAP", "craft",
        [src(VID30, 503, "Skywatcher's first-documented UAP class; tumbling black-body tetrahedron")],
        summary="Skywatcher class-1 UAP: tumbling/spinning high-speed black-bodied tetrahedron wearing a low/high-pressure vapor sheath that reflects sunlight. First sighting was a formation of seven during a 2021 government war-game."),
]
claims_30 = [
    ("skywatcher-origin-2021-wargame", 477,
     "Skywatcher's UAP discovery occurred by accident during a 2021 DoD-contracted war-game event; a formation of 7 Class-1 tetrahedral UAPs was observed over the blue/red-team exercise.",
     "person-james-valor", "personal_account",
     ["person-james-valor", "technology-class-one-tetrahedron", "concept-nine-uap-classes"],
     "At one of those war game events in 2021, we had an observation. It turned out to be class one UAPs. We originally thought that was a government made, US government made tool."),
    ("skywatcher-dog-whistle-summoning", 457,
     "Skywatcher's 'dog whistle' technology reliably summons UAPs at their location day after day; their sonic-lead Jordan predicts the class and conflict of next-day sightings.",
     "person-james-valor", "personal_account",
     ["person-james-valor", "concept-uap-dog-whistle", "concept-nine-uap-classes"],
     "After we turn on the dog whistle, UAPs literally come to us day after day. Jordan our sonic lead came up to me like, tomorrow we're going to see a conflict in the sky."),
    ("skywatcher-class-7-visual-purple", 489,
     "Skywatcher observed a Class-7 UAP with the naked eye hovering directly overhead — 'very glinty, looked metallic', purple or black through optics, with chrome-like reflections.",
     "person-james-valor", "personal_account",
     ["person-james-valor", "concept-nine-uap-classes"],
     "We had a class 7 UAP. Before the helo got here it came and hovered right over us. For the first time we saw a class 7 with a naked eye. It was very glinty, looked metallic."),
    ("skywatcher-hit-with-energy-weapon", 467,
     "A Skywatcher helicopter pursuing a Class-7 UAP was struck by an 'energy weapon' from the UAP mid-turn before the helicopter could orient toward it.",
     "person-james-valor", "personal_account",
     ["person-james-valor", "concept-nine-uap-classes"],
     "Mid-turn before he could actually turn it to the UAP, the UAP hit us with an energy weapon."),
    ("skywatcher-barber-collaboration", 469,
     "Skywatcher's origin and operations overlap with Jake Barber's retrieval program; Coulthart publicly disclosed Skywatcher's existence in his Barber interview.",
     "person-james-valor", "on_record_statement",
     ["person-james-valor", "person-jake-barber", "person-ross-coulthart"],
     "A mutual friend Jake Barber who gave me the honor of helping tell his story after Ross Coulthart came out as the first person to retrieve this craft of non-human origin. He mentioned he had this private enterprise he was working on called Skywatcher."),
    ("skywatcher-detection-spectrum-gap", 459,
     "Skywatcher confirms UAPs are emitting in narrow spectral bands that electro-optical sensors cannot see natively but cued cameras can — explaining 'UAPs visible on radar but invisible to naked eye.'",
     "person-james-valor", "on_record_statement",
     ["person-james-valor", "concept-nine-uap-classes"],
     "That little bit of extra is where they're actually emitting light. We have three spectrums and we see them on radar. We're sitting there with binoculars and can't see them."),
]

# ========== VIDEO 31: xnxasfyHtfo — Eric Weinstein × Eric Davis ==========
VID31 = "xnxasfyHtfo"
entities_31 = [
    P("eric-davis", "Eric Davis", VID31, 527,
      "Pentagon scientist; crash retrieval program confirmer",
      "Physicist with deep aerospace credentials (Aerospace Corporation, Earth Tech, NASA Lewis); claims direct personal knowledge of crash retrieval / non-human technology; has met ~5 people who worked on such programs.",
      ["Dr. Davis"], "physicist",
      ["scientist", "witness", "AATIP"]),
    document("weinstein-davis-dialogue", "Weinstein-Davis Dialogue (2024)", "transcript",
        [src(VID31, 527, "Debate between Weinstein and Davis on crash retrievals")],
        summary="Long-form Jesse Michels-mediated debate between Eric Weinstein (theoretical physicist) and Eric Davis (UFO-program insider) on the status and authenticity of crash retrieval programs."),
]
claims_31 = [
    ("davis-roswell-was-real", 531,
     "Eric Davis on camera asserts: 'The alleged Roswell crash was real. There was a there, there. It really happened.'",
     "person-eric-davis", "on_record_statement",
     ["person-eric-davis", "incident-1947-roswell", "concept-crash-retrieval"],
     "The alleged Roswell crash was real. There was a there there really happened."),
    ("davis-five-program-personnel", 543,
     "Davis states he has personally met approximately 5 people who worked on crash retrieval programs.",
     "person-eric-davis", "personal_account",
     ["person-eric-davis", "concept-crash-retrieval"],
     "How many of those crash retrieval program people have you met? I think it's five total."),
    ("weinstein-no-physics-in-retrieval", 551,
     "Weinstein challenges Davis: 'There's no physics in it. They're just — it defies the laws of physics. We haven't made progress. We have no physicists. How are they doing on this project decades in?'",
     "person-eric-weinstein", "on_record_statement",
     ["person-eric-weinstein", "person-eric-davis", "concept-crash-retrieval"],
     "There's no physics in it. It defies the laws of physics. We haven't made progress. We have no physicists. How are they doing on this project decades in?"),
    ("weinstein-not-manhattan-project", 555,
     "Weinstein rejects the Manhattan-Project framing of US reverse-engineering programs: 'This thing is not a Manhattan Project.'",
     "person-eric-weinstein", "on_record_statement",
     ["person-eric-weinstein", "program-manhattan-project", "concept-reverse-engineering"],
     "This thing is not a Manhattan project. And you know what the Manhattan project was?"),
    ("davis-wormhole-traversable", 523,
     "Eric Davis claims his research shows one should be able to create a traversable wormhole on demand, enabling transit to Alpha Centauri.",
     "person-eric-davis", "on_record_statement",
     ["person-eric-davis", "concept-alcubierre-drive"],
     "You're going to create a wormhole on demand. You should be able to. That's what my research showed."),
    ("weinstein-not-tweaking-gr", 557,
     "Weinstein criticizes physicists for not 'tweaking GR' — insisting current proposals are 'boring as sin' and the field has stagnated.",
     "person-eric-weinstein", "on_record_statement",
     ["person-eric-weinstein"],
     "Not one of these proposals excites me. They're boring as sin. I don't like GR. Why are you not tweaking it?"),
]

# ========== VIDEO 32: zrmG2jBckgk — Corrado Malanga, Giza scan ==========
VID32 = "zrmG2jBckgk"
entities_32 = [
    P("corrado-malanga", "Corrado Malanga", VID32, 589,
      "Italian researcher; Giza pyramid SAR-phonon scan lead",
      "Italian chemist and UFO researcher; head of the research group that developed the photon-phonon synthetic aperture radar technique for sub-surface earth scanning; scanned beneath the Giza pyramids and published the results.",
      ["Malanga"], "chemist / researcher",
      ["researcher", "Italy", "academic"]),
    P("zahi-hawass", "Zahi Hawass", VID32, 635,
      "Former Egyptian Minister of Culture; pyramid gatekeeper",
      "Former Egyptian Minister of Culture; historically blocked alternative-archaeology investigations of the Sphinx enclosure and subterranean Giza.",
      ["Hawass", "Zahi Was"], "egyptologist", ["Egypt", "official"]),
    concept("photon-phonon-sar", "Photon-Phonon Synthetic Aperture Radar", "technology",
        [src(VID32, 605, "Malanga's technique combining SAR and phonon (earth vibration) data")],
        summary="Malanga's team's imaging technique combining photon-based synthetic aperture radar (from satellites like COSMO-SkyMed) with earth-vibration phonon data; enables sub-surface tomographic imaging to kilometer depth with sub-meter resolution."),
    concept("giza-subterranean-tubes", "Giza Subterranean Tube-Spiral Structures", "technology",
        [src(VID32, 585, "Malanga's imaging of tube structures with spiral interiors beneath pyramids")],
        summary="Per Malanga's SAR-phonon scan: beneath the Khafre (middle) pyramid are tube-like structures with spiral interiors (possibly piezoelectric material) descending over 1 km deep and connecting to four +4 cube chambers and ~80m-wide chambers at depth."),
]
claims_32 = [
    ("malanga-1km-depth-tubes", 585,
     "Malanga's SAR-phonon scan detected tube structures with spiral interiors beneath the Khafre pyramid descending over a kilometer in depth.",
     "person-corrado-malanga", "personal_account",
     ["person-corrado-malanga", "concept-giza-subterranean-tubes",
      "concept-photon-phonon-sar"],
     "The structures are like tubes that are connected to the base of the Khafre pyramid to something that is located — over 1 kilometer of depth."),
    ("malanga-80m-chambers", 597,
     "The scan also detected ~80m-wide chambers with 4+4 cube arrangements in subterranean Giza — massive artificial-seeming void structures.",
     "person-corrado-malanga", "personal_account",
     ["person-corrado-malanga", "concept-giza-subterranean-tubes"],
     "Huge chambers for approximately 80 m wide on the bottom. Tubes that are connected to four + four cubes that are descending."),
    ("malanga-piezoelectric-spirals", 585,
     "Malanga posits the spiral structures beneath the pyramid may be made of piezoelectric material — implying intentional engineered function rather than natural geology.",
     "person-corrado-malanga", "speculation",
     ["person-corrado-malanga", "concept-giza-subterranean-tubes"],
     "The spirals are made by piezoelectric material."),
    ("sar-phonon-technique-novel", 605,
     "Malanga's photon-phonon synthetic-aperture-radar technique is novel; conventional SAR cannot penetrate earth subsurface — his team combined photon and phonon propagation at material boundaries to enable tomographic inversion.",
     "person-corrado-malanga", "cited_from_document",
     ["person-corrado-malanga", "concept-photon-phonon-sar"],
     "Radar synthetic aperture cannot penetrate the earth. We have developed a new technique combining photon and phonon at the boundary. Tomographic inversion."),
    ("malanga-cosmo-skymed-data", 601,
     "Malanga's team used Italian Space Agency COSMO-SkyMed satellite data plus National Research Council of Italy collaboration for the Giza sub-surface imaging.",
     "person-corrado-malanga", "personal_account",
     ["person-corrado-malanga", "concept-photon-phonon-sar"],
     "We have COSMO-SkyMed affiliated to the Italian space agency. Data produced by these satellites to perform. National Research Council of Italy."),
    ("malanga-for-humanity-open-source", 631,
     "Malanga's Giza work was motivated 'for humanity' — published open-source with no commercial intent; his book documents full methodology.",
     "person-corrado-malanga", "personal_account",
     ["person-corrado-malanga"],
     "We were motivated very motivated to humanity. According to my friend in 2019 Corrado Malanga. Everything is open source."),
]


if __name__ == "__main__":
    print("Extending videos 23-32...")
    extend(VID23, entities_23, claims_23)
    extend(VID24, entities_24, claims_24)
    extend(VID25, entities_25, claims_25)
    extend(VID26, entities_26, claims_26)
    extend(VID27, entities_27, claims_27)
    extend(VID28, entities_28, claims_28)
    extend(VID29, entities_29, claims_29)
    extend(VID30, entities_30, claims_30)
    extend(VID31, entities_31, claims_31)
    extend(VID32, entities_32, claims_32)
    print("Done.")
