"""Deep claim extraction for videos 13-22."""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _extract_v1_builders import (
    src, claim, edge, person, incident, technology, concept, document,
    event, program, location, phenomenon
)
from _extract_helpers import write_output


def extend(vid: str, new_entities: list[dict], claims_data: list[tuple]) -> None:
    path = Path(__file__).parent / "entities" / f"{vid}.json"
    existing = json.loads(path.read_text())
    nodes: list[dict] = list(existing["nodes"])
    edges_list: list[dict] = list(existing["edges"])
    ids = {n["id"] for n in nodes}

    def S(t=0, q=""):
        return [src(vid, t, None, q)]

    for e in new_entities:
        if e["id"] not in ids:
            nodes.append(e)
            ids.add(e["id"])

    for slug, t, stmt, asserter, assertability, subs, quote in claims_data:
        cl = claim(slug, stmt, asserter, vid, t, assertability, subs,
                   S(t, quote), quote=quote)
        nodes = [n for n in nodes if n["id"] != cl["id"]]
        ids.discard(cl["id"])
        nodes.append(cl)
        ids.add(cl["id"])
        edges_list.append(edge(asserter, cl["id"], "ASSERTED",
                              S(t, stmt[:200]), 0.95))
        edges_list.append(edge(f"video-{vid}", cl["id"], "REFERENCES",
                              S(t), 0.95))
        for subj in subs:
            if subj != asserter and subj != f"video-{vid}":
                edges_list.append(edge(cl["id"], subj, "REFERENCES",
                                      S(t), 0.85))

    out = {"video_id": vid, "nodes": nodes, "edges": edges_list}
    write_output(out, vid)
    print(f"  {vid}: {len(nodes)} nodes, {len(edges_list)} edges")


def P(slug, label, vid, t, quote, summary, aliases=None, prof="", notability=None):
    return person(slug, label, [src(vid, t, None, quote)],
                  summary=summary, aliases=aliases or [], profession=prof,
                  notability=notability or [])


# ========== VIDEO 13: 73YBwFvcmF8 — Mario Woods / Ellsworth ==========
VID13 = "73YBwFvcmF8"
entities_13 = [
    P("mario-woods", "Mario Woods", VID13, 10,
      "Former US Air Force Security Police at Ellsworth AFB Nov 1977 abductee",
      "Former US Air Force Security Police officer stationed at Ellsworth AFB 1977; experienced a UFO encounter with missing time and physical marks at November 5 missile site near Sturgis, South Dakota.",
      ["Woods"], "military veteran",
      ["witness", "experiencer", "USAF", "abductee", "Ellsworth"]),
    P("michael-johnson-ellsworth", "Michael Johnson (USAF partner)", VID13, 22,
      "USAF Security Police partner to Mario Woods during Nov 1977 incident",
      "US Air Force Security Police officer working vacation relief at Ellsworth; Woods' partner on the night of the November 1977 incident.",
      [], "military veteran", ["witness", "USAF"]),
    P("bill-hollman", "Bill Hollman", VID13, 43,
      "USAF Staff Sergeant, Flight Security Controller at Ellsworth November site",
      "US Air Force Staff Sergeant and Flight Security Controller on duty at the November 1977 Ellsworth missile facility.",
      [], "military veteran", ["USAF"]),
    incident("1977-ellsworth-november-5", "November 1977 Ellsworth 'November-5' Missile Site UFO",
             "abduction", "1977-11-17",
             [src(VID13, 11, "Missing time incident at November 5 missile site near Sturgis")],
             summary="Nov 1977 UFO encounter at Ellsworth AFB's November-5 Minuteman II missile site in South Dakota. Witnessed by USAF SP Mario Woods; involved signaling exchange, hovering sphere, and missing time."),
    location("ellsworth-november-5-site", "Ellsworth November-5 Missile Site",
             "military_base",
             [src(VID13, 13, "Minute Man II missile silo north of Sturgis, SD")],
             country="US", state="South Dakota"),
]
claims_13 = [
    ("woods-blast-door-sphere", 9,
     "Mario Woods describes a sphere roughly the size of a Walmart building hovering ~10 ft above the blast door of the November-5 Minuteman II silo at Ellsworth.",
     "person-mario-woods", "personal_account",
     ["person-mario-woods", "location-ellsworth-november-5-site",
      "incident-1977-ellsworth-november-5"],
     "There sat this object on top of November 5 that was about 10 ft in the air directly on top of that blast door that was the size of a Walmart building. It was huge and it was a sphere."),
    ("woods-signal-exchange", 47,
     "Woods flashed his facility lights three times; the UFO flashed back in the same pattern — then repeated with a three-two-three sequence — confirming two-way signaling.",
     "person-mario-woods", "personal_account",
     ["person-mario-woods", "incident-1977-ellsworth-november-5"],
     "I just flipped it off and on off and on off and on three times. It goes out on out on out and on. It just sent shivers up me. They do see me."),
    ("woods-prp-clearance", 19,
     "Woods was cleared under the USAF Personal Reliability Program (PRP) — explicit vetting of mental-health stability required to work around nuclear weapons.",
     "person-mario-woods", "personal_account",
     ["person-mario-woods", "organization-us-air-force"],
     "I was part of the personal reliability program also for sensitive nuclear equipment. They really analyze you deeply to see if you can't do that."),
    ("woods-collie-catatonic-shock", 11,
     "Woods' dog (a collie) was found in catatonic shock for hours after the incident — corroborating a physical disturbance beyond subjective human report.",
     "person-mario-woods", "personal_account",
     ["person-mario-woods", "incident-1977-ellsworth-november-5"],
     "A collie locked in catatonic shock for hours literally could not get a breath of air it was just all encompassing."),
    ("woods-missing-time-physical-marks", 11,
     "Woods' incident left him with missing time and physical marks on his body — classic abduction-case physical signatures.",
     "person-jesse-michels", "on_record_statement",
     ["person-mario-woods", "phenomenon-lost-time"],
     "Literally leaving him with missing time marks on his body."),
]

# ========== VIDEO 14: 0qlppHc3-gg — Ky Dickens / Telepathy Tapes ==========
VID14 = "0qlppHc3-gg"
entities_14 = [
    P("ky-dickens", "Ky Dickens", VID14, 85,
      "Documentary filmmaker behind The Telepathy Tapes",
      "Documentary filmmaker (5 feature films) behind The Telepathy Tapes podcast/series documenting telepathic communication in autistic non-speaking children.",
      ["Dickens", "Kai"], "filmmaker",
      ["filmmaker", "investigator"]),
    P("diane-powell", "Diane Powell", VID14, 87,
      "Harvard-trained neuroscientist studying autistic savant telepathy",
      "Harvard-trained neuroscientist who researches autistic savants with claimed telepathic abilities; central expert in The Telepathy Tapes.",
      ["Dr. Powell"], "neuroscientist",
      ["scientist", "Harvard", "researcher"]),
    P("oliver-sacks", "Oliver Sacks", VID14, 113,
      "Neurologist, author of Awakenings, studied autistic savants",
      "Neurologist and author (Awakenings, The Man Who Mistook His Wife for a Hat). Diane Powell met him in 1986; introduced her to autistic savants.",
      ["Sacks"], "neurologist",
      ["scientist", "author", "historical"]),
    P("mia-telepathy-mexico", "Mia (Telepathy Tapes subject)", VID14, 91,
      "Young non-speaking autistic girl from Monterrey Mexico tested telepathically",
      "Young non-speaking autistic girl from Monterrey Mexico brought to Glendale CA for controlled telepathy tests in The Telepathy Tapes.",
      [], "", ["experiencer", "child", "autistic"]),
    P("amelia-telepathy", "Amelia (Telepathy Tapes subject)", VID14, 127,
      "Non-speaking autistic girl featured in episode 7 of The Telepathy Tapes",
      "Non-speaking autistic girl featured in episode 7 of The Telepathy Tapes.",
      [], "", ["experiencer", "child", "autistic"]),
    document("telepathy-tapes-series", "The Telepathy Tapes", "broadcast",
        [src(VID14, 83, "Podcast/documentary series documenting autistic telepathy")],
        summary="Ky Dickens' podcast/documentary series documenting controlled tests of telepathic communication in autistic non-speaking children.",
        author="Ky Dickens"),
    document("awakenings-sacks", "Awakenings", "book",
        [src(VID14, 115, "Oliver Sacks book; introduced Powell to autistic savants")],
        summary="Oliver Sacks' book on Parkinson's patients treated with L-DOPA; part of his body of work on unusual neurological syndromes.",
        author="Oliver Sacks"),
    concept("autistic-telepathy", "Autistic Savant Telepathy", "metaphysics",
        [src(VID14, 83, "Non-speaking autistic children demonstrating telepathic ability")],
        summary="Phenomenon documented across many independent families: non-speaking autistic children demonstrating statistically significant telepathic reception of numbers, words, images — validated in controlled tests."),
]
claims_14 = [
    ("dickens-telepathy-tapes-thesis", 83,
     "Ky Dickens asserts that non-speaking autistic children demonstrate statistically significant telepathic abilities under controlled conditions, documented across many independent families.",
     "person-ky-dickens", "on_record_statement",
     ["person-ky-dickens", "document-telepathy-tapes-series",
      "concept-autistic-telepathy"],
     "Autistic individuals have these incredible abilities. The science behind this is so much bigger than our knee-jerk reactions of truth."),
    ("mia-controlled-glendale-test", 91,
     "Dickens rented a Glendale CA house; removed mirrors and TVs; blindfolded Mia; partitioned her from her mother; tested with random number/picture generators — Mia was accurate every time.",
     "person-ky-dickens", "personal_account",
     ["person-ky-dickens", "person-mia-telepathy-mexico",
      "person-diane-powell", "concept-autistic-telepathy"],
     "We rented a house in Glendale California and we took all the mirrors down and all the TVs down. We'd blindfold Mia. She was right every time."),
    ("popsicle-stick-test-beyond-telepathy", 147,
     "The popsicle-stick test had Mia correctly pile sticks while blindfolded — Dickens notes this goes BEYOND telepathy because no one was 'sending' information; suggests clairvoyance.",
     "person-ky-dickens", "personal_account",
     ["person-ky-dickens", "person-mia-telepathy-mexico",
      "concept-autistic-telepathy"],
     "Popsicle stick tests which was beyond telepathy because no one's sending information. She could see them blind perfect blindfold."),
    ("powell-email-flood-from-parents", 111,
     "Diane Powell's inbox contains hundreds of emails from independent, siloed parents describing their non-speaking autistic child reading their thoughts — convincing Dickens this is widespread.",
     "person-diane-powell", "personal_account",
     ["person-diane-powell", "concept-autistic-telepathy"],
     "Her email box was filled of parents reaching out saying I'm finding that my child can read my thoughts this seems impossible."),
    ("sacks-twin-prime-numbers", 117,
     "Oliver Sacks documented institutionalized autistic twins exchanging six-digit prime numbers with no algorithm — 'they just saw them' — foreshadowing extra-cognitive savant abilities.",
     "person-diane-powell", "cited_from_document",
     ["person-oliver-sacks", "person-diane-powell", "document-awakenings-sacks"],
     "These twins who are institutionalized who were autistic who played a game in which they would say prime numbers back and forth to one another. They just knew these prime numbers and they just saw them."),
    ("covid-homeschooling-revealed-telepathy", 127,
     "During COVID homeschooling, two independent families (Mia's and Amelia's) discovered their child's telepathic ability once parents spent extended one-on-one time — ability hadn't manifested in school.",
     "person-ky-dickens", "cited_from_document",
     ["person-ky-dickens", "person-mia-telepathy-mexico", "person-amelia-telepathy",
      "concept-autistic-telepathy"],
     "Two families - both Mia and another girl Amelia - when the parents were homeschooling with covid and they had to spend tons of time with their child all of a sudden their child started spelling on iPads doing things they weren't ever doing in school."),
    ("non-speakers-spiritual-gift-framing", 135,
     "Non-speaking autistic children in The Telepathy Tapes universally describe their telepathic ability as a 'spiritual gift from God' — not pathological or demonic.",
     "person-ky-dickens", "on_record_statement",
     ["person-ky-dickens", "concept-autistic-telepathy"],
     "What the non-speakers would say is this is a spiritual gift from God that is I think what every single one would say."),
]

# ========== VIDEO 15: dnnpyNuPdXs — Jake Barber / helicopter retrieval ==========
VID15 = "dnnpyNuPdXs"
entities_15 = [
    P("jake-barber", "Jake Barber", VID15, 157,
      "Former USAF Combat Control helicopter pilot claiming firsthand UFO retrieval",
      "Former USAF Combat Control operator. Claims he piloted helicopters to retrieve non-human-origin craft ('eggs'); signed a 10-year Guaranteed Training Education (GTE) contract in 1994 at age 17.",
      ["Barber"], "military veteran / pilot",
      ["whistleblower", "USAF", "pilot", "AARO"]),
    program("gte-air-force-10year", "USAF Guaranteed Training Education (GTE)",
        [src(VID15, 207, "Brand-new 10-year contract fasttracking Barber into Combat Control")],
        summary="USAF Guaranteed Training Education program — a 10-year fasttrack contract for special-operations/Combat-Control training, historically unusual. Barber signed at age 17 in 1994.",
        acronym="GTE"),
    concept("egg-craft-retrieval", "Egg-shape NHI Craft Retrieval", "technology",
        [src(VID15, 167, "Barber describes retrieving 20ft egg-shaped craft via helicopter")],
        summary="Class of non-human-origin craft with egg morphology, ~20ft in size, which Barber claims to have retrieved via helicopter operations — and demonstrated post-program in broad daylight in August (reportedly with AARO involvement)."),
    concept("four-eyes-intel-profile", "Four-I Intel Recruitment Profile", "psychology",
        [src(VID15, 179, "Imagination, intellect, intuition, instincts")],
        summary="Barber's term for the cognitive profile (imagination, intellect, intuition, instincts) that the US intelligence community allegedly targets for recruitment into covert programs."),
    concept("comfort-and-chaos", "Comfort-and-Chaos", "psychology",
        [src(VID15, 205, "Barber scored higher on stressed IQ test than baseline")],
        summary="Barber's psychological model derived from scoring 152 on an oxygen-deprived stress IQ test (vs 138 baseline); suggests chaos-mode cognition is his functional mode — characteristic targeted by intel recruiters."),
]
claims_15 = [
    ("barber-retrieved-nhi-craft", 163,
     "Barber states on camera he has piloted helicopters to retrieve non-human-origin craft; operations use GPS coordinates fed to him at the last moment with a terse description enroute.",
     "person-jake-barber", "on_record_statement",
     ["person-jake-barber", "concept-crash-retrieval", "concept-egg-craft-retrieval"],
     "Have you retrieved a non-human craft? Yes, I have. I sit back at a separate location. I get GPS coordinates at the very last second. I get dispatched."),
    ("barber-egg-demonstrated-aaro-august", 169,
     "Post-program, working now with AARO, Barber claims he 'elicited' an egg-shaped craft that flew by in broad daylight at ~10,000 mph silently, demonstrated in August.",
     "person-jake-barber", "personal_account",
     ["person-jake-barber", "program-aaro", "concept-egg-craft-retrieval"],
     "Since we've left the program and reorganized and are now working with AARO, I can make the egg show up. The egg flies by in dead silence, moving at 10,000 miles an hour."),
    ("barber-gte-contract-age-17", 207,
     "Barber signed a 10-year GTE contract in 1994 at age 17 — two and a half years of pre-selected special-operations training, historically unprecedented.",
     "person-jake-barber", "personal_account",
     ["person-jake-barber", "program-gte-air-force-10year"],
     "I signed a contract for combat control in 1994. I was recruited to a brand new program that was called GTE. 10-year contract that would fasttrack me through special operations training."),
    ("barber-stress-iq-152", 203,
     "Barber scored 138 baseline but 152 on a stressed IQ test (oxygen-mask-sealed) — leading to the 'comfort-and-chaos' recruitment framework.",
     "person-jake-barber", "personal_account",
     ["person-jake-barber", "concept-comfort-and-chaos"],
     "The first time I took an IQ test it was like 138. Second thing which is a stress IQ test — oxygen mask that sealed my face with no air coming to it. I tested 152."),
    ("air-force-blue-black-line-1947", 211,
     "Barber frames the USAF as the 'blue-black line' agency since its 1947 inception — created alongside CIA, NSA, and DoD right after the Roswell incident.",
     "person-jake-barber", "speculation",
     ["person-jake-barber", "organization-us-air-force", "organization-cia",
      "incident-1947-roswell"],
     "The Air Force is this agency that straddled the blue black line since its inception in 1947, like two weeks after Roswell incident you get the National Security Act, you get the formation of the Air Force, CIA at the same time."),
    ("barber-deaths-in-program", 171,
     "Barber states people connected to the retrieval programs who tried to come public have died; an active investigation constrains what he can disclose.",
     "person-jake-barber", "on_record_statement",
     ["person-jake-barber", "concept-crash-retrieval"],
     "There are people that have died who were coming out and who were speaking out on our activities."),
    ("barber-inner-not-outer-space", 175,
     "Barber reframes NHI not as purely extraterrestrial: 'outer space versus inner space is all the same' — implying consciousness-based interpretation.",
     "person-jake-barber", "speculation",
     ["person-jake-barber", "concept-nhi"],
     "The real implications are way more powerful. It's realizing that there is something else out there that's maybe not extra at all. It's something that's part of us."),
]

# ========== VIDEO 16: aKZ_MUbuk_Q — Riz Virk / simulation hypothesis ==========
VID16 = "aKZ_MUbuk_Q"
entities_16 = [
    P("riz-virk", "Rizwan Virk", VID16, 255,
      "MIT/Stanford computer scientist, game entrepreneur, simulation theorist",
      "MIT and Stanford educated computer scientist; successful video-game entrepreneur; author of The Simulation Hypothesis and books extending Bostrom's simulation theory with physics, information theory, and cross-religious commentary.",
      ["Virk", "Riz", "Rizwan"], "computer scientist",
      ["scientist", "entrepreneur", "author"]),
    P("philip-k-dick", "Philip K. Dick", VID16, 239,
      "Sci-fi author, early simulation-reality proponent",
      "Sci-fi author; early proponent of simulation/altered-reality fiction (e.g., Ubik, Man in the High Castle); cited as founding intellectual ancestor of modern simulation theory.",
      ["PKD", "Dick"], "author",
      ["author", "historical"]),
    P("william-gibson", "William Gibson", VID16, 239,
      "Cyberpunk sci-fi author",
      "Cyberpunk sci-fi author (Neuromancer); early proponent of simulated/virtual-reality themes in fiction.",
      ["Gibson"], "author", ["author"]),
    P("nick-bostrom", "Nick Bostrom", VID16, 239,
      "Oxford philosopher; author of simulation-hypothesis paper and Superintelligence",
      "Oxford philosopher; author of 'Are You Living in a Computer Simulation?' (2003) and Superintelligence (2014). Central academic voice on simulation theory.",
      ["Bostrom"], "philosopher",
      ["philosopher", "academic"]),
    P("john-wheeler", "John Wheeler", VID16, 261,
      "Physicist of the 'it from bit' hypothesis",
      "American theoretical physicist; coined 'it from bit' framework: reality is fundamentally informational, answered by a series of yes/no questions.",
      ["Wheeler"], "physicist",
      ["physicist", "historical"]),
    P("claude-shannon", "Claude Shannon", VID16, 295,
      "Architect of information theory",
      "American mathematician; founder of information theory (Shannon bits, mutual information); theoretical foundation of modern computation and the simulation argument.",
      ["Shannon"], "mathematician",
      ["mathematician", "historical"]),
    concept("simulation-multiverse", "Simulated Multiverse", "metaphysics",
        [src(VID16, 269, "Virk's extension of the simulation hypothesis across the Multiverse")],
        summary="Virk's hypothesis that all possible constant-values have been simulated across a multiverse of timelines; the observed fine-tuning is our surviving branch."),
    concept("mandela-effect", "Mandela Effect", "metaphysics",
        [src(VID16, 285, "Collective misremembered 'facts' across scripture and pop culture")],
        summary="Phenomenon where large groups remember events that never occurred. Named after Nelson Mandela dying in prison (he didn't). Virk catalogues Bible, Quran, Star Wars, Berenstein/Berenstain Bears changes."),
    concept("jin-beings", "Jin (time-shifting beings)", "metaphysics",
        [src(VID16, 293, "Sufi framework: beings that can change physical objects but not memory")],
        summary="Per a Sufi Imam cited by Virk: beings that exist outside normal spacetime, can change physical objects but cannot change memory — proposed as mechanism behind the Mandela Effect and requirement to memorize scripture word-for-word."),
    document("superintelligence-bostrom", "Superintelligence", "book",
        [src(VID16, 239, "Nick Bostrom's 2014 book")],
        summary="Bostrom's 2014 academic treatment of AI safety and the simulation argument.",
        author="Nick Bostrom", year=2014),
    document("simulation-hypothesis-virk", "The Simulation Hypothesis", "book",
        [src(VID16, 255, "Virk's central work")],
        summary="Rizwan Virk's primary book extending Bostrom's simulation argument with physics, information theory, and cross-religious commentary.",
        author="Rizwan Virk"),
    document("sex-in-the-city-mandela", "Collective Mandela-Effect Catalog", "paper",
        [src(VID16, 287, "Virk's catalog of Mandela-Effect examples including scripture")],
        summary="Virk's body of catalog work on the Mandela Effect: scripture changes (Isaiah's lion and lamb), pop-culture changes (Sex and the City, Berenstein Bears, Empire Strikes Back 'Luke I am your father' vs 'No I am your father')."),
]
claims_16 = [
    ("virk-simulation-hypothesis", 259,
     "Virk's central thesis: physical reality is best modeled as an informational simulation rendered 'just in time' for observers; physics (Wheeler's it-from-bit, quantum indeterminacy) supports this framing.",
     "person-riz-virk", "on_record_statement",
     ["person-riz-virk", "person-john-wheeler", "person-nick-bostrom",
      "concept-simulation-hypothesis"],
     "The more I looked into the idea of the physical universe the more I realized that many physicists are telling us that the physical world doesn't really exist."),
    ("musk-one-in-billions-simulation", 255,
     "Elon Musk has publicly stated the odds we're in base reality are 'one in billions' — aligning with the simulation hypothesis.",
     "person-jesse-michels", "cited_from_document",
     ["concept-simulation-hypothesis"],
     "Even Elon Musk - 'There's a one in billion chance that this is based reality.'"),
    ("tyson-50-pct-simulation", 257,
     "Neil deGrasse Tyson has publicly accepted the simulation hypothesis is ~50% likely.",
     "person-jesse-michels", "cited_from_document",
     ["person-neil-degrasse-tyson", "concept-simulation-hypothesis"],
     "Even a totally close-minded midwit like Neil deGrasse Tyson accepts that we are 50% likely to be living in a simulation."),
    ("virk-fibonacci-golden-ratio-code", 275,
     "Virk cites Fibonacci/Golden-Ratio patterns recurring across DNA dimensions, leaf arrangements, and galactic spiral arms as evidence of reused procedural code across biological and cosmological scales.",
     "person-riz-virk", "on_record_statement",
     ["person-riz-virk", "concept-simulation-hypothesis"],
     "The dimensions of DNA follow Fibonacci numbers. Biological patterns often look like fractals of larger cosmological patterns — spiral galaxies form logarithmic spirals displaying the golden ratio."),
    ("virk-binary-matter-antimatter", 281,
     "Virk points to matter/antimatter particle pairs and DNA base-pairing (A-T, C-G) as evidence of binary structure analogous to bits in a simulation.",
     "person-riz-virk", "on_record_statement",
     ["person-riz-virk", "concept-simulation-hypothesis"],
     "Where might we find ones and zeros in nature? Plenty of particles have matter antimatter pairs. We all have four nucleotides A-T C-G — base pairs like bits."),
    ("virk-jin-mandela-explanation", 293,
     "Per a Sufi Imam Virk interviewed, the reason Quran must be memorized word-for-word is that 'jin' can change physical objects (books, scripture) but not human memory — this explains Mandela-effect scripture changes.",
     "person-riz-virk", "hearsay",
     ["person-riz-virk", "concept-mandela-effect", "concept-jin-beings"],
     "There are these entities out there who don't live in normal space and time the way we do. They can go back and change physical objects but they're not allowed to change our memory. Those beings are called jin."),
    ("virk-render-only-observable", 231,
     "Rendering optimization in 3D MMO RPG games — 'render only that which can be observed by the avatar' — Virk uses this to explain quantum wave-function collapse upon observation.",
     "person-riz-virk", "on_record_statement",
     ["person-riz-virk", "concept-simulation-hypothesis",
      "concept-holographic-principle"],
     "The rule of thumb in video games for 3D MMO RPGs is render only that which can be observed by the avatar."),
]

# ========== VIDEO 17: 09KP8XVf5nY — Harald Malmgren ==========
VID17 = "09KP8XVf5nY"
entities_17 = [
    P("harald-malmgren", "Harald Malmgren", VID17, 307,
      "Presidential advisor to JFK, LBJ, Nixon, Ford; handled UFO material",
      "American economist, presidential advisor to JFK, LBJ, Nixon, and Ford; McNamara 'whiz kid' at age 27 during Cuban Missile Crisis. Claims to have directly handled UFO material recovered from 1963 Marshall Islands nuclear test plume. Died days after final interview with Michels.",
      ["Malmgren", "Harold Malmgren"], "economist / presidential advisor",
      ["official", "witness", "experiencer", "historical"]),
    P("pippa-malmgren", "Pippa Malmgren", VID17, 319,
      "Harald's daughter; George W. Bush national economic council",
      "Daughter of Harald Malmgren; Special Assistant to President George W. Bush on the National Economic Council.",
      ["Pippa"], "economist", ["official"]),
    P("robert-mcnamara", "Robert McNamara", VID17, 307,
      "Secretary of Defense during Cuban Missile Crisis",
      "US Secretary of Defense 1961-1968; brought Malmgren into the Cuban Missile Crisis situation room at age 27.",
      ["McNamara"], "official",
      ["DoD", "historical"]),
    P("richard-bissell", "Richard Bissell", VID17, 317,
      "CIA Deputy Director of Plans; chief architect of Area 51",
      "CIA Deputy Director for Plans; chief architect of Area 51 / Groom Lake and the U-2 program. Per Malmgren, confirmed the 1933 Magenta (Italy) UFO crash.",
      ["Bissell"], "intelligence director",
      ["CIA", "historical", "Area 51"]),
    P("james-angleton", "James Jesus Angleton", VID17, 327,
      "CIA Chief of Counterintelligence",
      "CIA Chief of Counterintelligence 1954-1975; deep historical UAP-secrecy-network figure. Connection to Knights of Malta via Angleton's father per Malmgren.",
      ["Angleton"], "intelligence officer",
      ["CIA", "historical"]),
    P("carl-compton", "Karl Compton", VID17, 357,
      "MIT President who recruited Malmgren at age 13",
      "MIT President; WWII-era head of War Production Board. Recruited 13-year-old Malmgren directly into MIT with a full scholarship after meeting him painting walls at a Newport mansion.",
      ["Compton"], "physicist / academic",
      ["MIT", "scientist", "historical"]),
    incident("1963-marshall-islands-ufo-material", "1963 Marshall Islands Nuclear Plume UFO Material Recovery",
             "crash_retrieval", "1963-10-01",
             [src(VID17, 315, "Malmgren directly handled UFO material from Marshall Islands nuclear test")],
             summary="Non-terrestrial material recovered from the plume of a US Marshall Islands nuclear test in late 1963 and directly handled by Harald Malmgren."),
    incident("1933-magenta-italy-crash", "1933 Magenta (Italy) UFO Crash", "crash_retrieval", "1933-01-01",
             [src(VID17, 317, "Mussolini-era UFO crash confirmed by Richard Bissell to Malmgren")],
             summary="Alleged 1933 crash of a UFO in Magenta, Italy; recovered by Mussolini's government; confirmed as genuine to Malmgren by CIA's Richard Bissell."),
]
claims_17 = [
    ("malmgren-handled-ufo-material", 315,
     "Malmgren on camera states he directly handled anomalous material that fell from the plume of a US Marshall Islands nuclear test in late 1963 — first presidential-advisor-caliber admission of direct UFO material handling.",
     "person-harald-malmgren", "on_record_statement",
     ["person-harald-malmgren", "incident-1963-marshall-islands-ufo-material",
      "phenomenon-nhi-biologics"],
     "Harold admits to directly handling UFO material that fell out of the plume of a Marshall Islands nuclear test. This is world history. It's the first time anybody of this caliber has ever admitted to handling UFO material directly."),
    ("bissell-confirmed-magenta-1933", 317,
     "Richard Bissell (CIA architect of Area 51) personally confirmed to Malmgren the existence of the 1933 Magenta Italy UFO crash subsequently reported by David Grusch.",
     "person-harald-malmgren", "on_record_statement",
     ["person-harald-malmgren", "person-richard-bissell",
      "incident-1933-magenta-italy-crash", "person-david-grusch"],
     "Richard Bissell mentioned the 1933 Magenta crash. Tells me Bissell confirmed the existence of the magenta UFO crash of 1933 in Italy recently reported on by UFO whistleblower David Grush."),
    ("malmgren-mj12-tracked-from-youth", 319,
     "Malmgren implies the Majestic-12 tracked him from his youth; attributes his out-of-nowhere meetings with elites (Putin, etc.) to deliberate network placement.",
     "person-harald-malmgren", "personal_account",
     ["person-harald-malmgren", "program-mj-12"],
     "Your name written in all the important books of talent keeps not only CI but you know all the majestic all these guardians. Malmgren implies he was being tracked by the majestic 12 from a young age."),
    ("malmgren-lemay-cuban-missile", 311,
     "In the Cuban Missile Crisis situation room (age 27), Malmgren rhetorically cornered General Curtis LeMay with the question 'what would be your prime target first?' — LeMay slammed his papers down and stormed out, de-escalating the nuclear confrontation.",
     "person-harald-malmgren", "personal_account",
     ["person-harald-malmgren", "person-curtis-lemay",
      "person-robert-mcnamara"],
     "I said, 'It's madness. If you hit Moscow, there's no one to talk to.' Lame literally got up and slammed his papers down. I refuse to run with this."),
    ("malmgren-compton-mit-full-ride", 353,
     "Karl Compton (MIT President, WWII War Production Board head) offered 13-year-old Malmgren a full MIT scholarship after a single conversation in which Malmgren independently described photon-entanglement concepts that weren't experimentally proven until the 1960s-70s.",
     "person-harald-malmgren", "personal_account",
     ["person-harald-malmgren", "person-carl-compton"],
     "I want to take this boy out of your school. I want to come in September and matriculate at MIT. We'll give him a full scholarship. He was saying this at the age of 14 in 1950."),
    ("malmgren-jfk-ufo-assassination-link", 329,
     "Asked whether UFOs played a role in JFK's death, Malmgren answers 'Yes — I think it was probably the number one issue.'",
     "person-harald-malmgren", "on_record_statement",
     ["person-harald-malmgren", "person-jfk", "event-jfk-mccone-letter"],
     "Do you think UFOs played any part in JFK's death? Yes. I think it was probably the number one issue."),
    ("pippa-three-body-problem-mandatory-reading", 325,
     "Per Pippa Malmgren: The Three-Body Problem became mandatory reading among high-level US national security advisers in the Bush 43 era — UAP disclosure discussions revolved around its 'dark forest' framing.",
     "person-pippa-malmgren", "personal_account",
     ["person-pippa-malmgren", "document-three-body-problem",
      "concept-disclosure"],
     "A lot of these high-level disclosure discussions revolved around one particular book, a Chinese science fiction novel called The Three-Body Problem, which became mandatory reading among many high-level national security advisers."),
    ("bush43-hadley-contemplated-disclosure", 323,
     "Per Hal Puthoff (public), George W. Bush contemplated UFO disclosure with his National Security Advisor Stephen Hadley — corroborated by Pippa.",
     "person-jesse-michels", "cited_from_document",
     ["person-pippa-malmgren", "person-hal-puthoff", "concept-disclosure"],
     "Through Hal Puthoff that George W. Bush contemplated UFO disclosure with his national security adviser Stephen Hadley."),
]

# ========== VIDEO 18: 1zRWi_r3HRM — Beatriz Villarroel / 100K transients ==========
VID18 = "1zRWi_r3HRM"
entities_18 = [
    P("beatriz-villarroel", "Beatriz Villarroel", VID18, 391,
      "Stockholm University astronomer; Palomar transients discovery",
      "Swedish astrophysicist; PhD astrophysics; L'Oreal-UNESCO Women in Science prize; Associate Professor at Stockholm University. Detected ~105,000 unidentified transient objects in 1950s Palomar plates — pre-Sputnik.",
      ["Villarroel", "Beatriz", "Voriel", "Valale"], "astrophysicist",
      ["scientist", "astronomer", "academic"]),
    P("enrique-solano", "Enrique Solano", VID18, 439,
      "Spanish astronomer, co-discovered July 19 1952 transient triplet",
      "Spanish astronomer; collaborator with Villarroel; discovered the July 19 1952 three-transient Palomar example.",
      ["Solano"], "astronomer", ["scientist"]),
    P("steven-bruehl", "Steven Bruehl", VID18, 407,
      "Vanderbilt PhD correlating Palomar transients with nuclear tests",
      "Vanderbilt PhD who replicated and extended Villarroel's Palomar transients work, correlating them with historical nuclear tests and public UAP sightings.",
      ["Bruell", "Bruehl"], "scientist", ["scientist", "Vanderbilt"]),
    location("palomar-observatory", "Palomar Observatory", "observation_site",
        [src(VID18, 387, "Most prominent pre-satellite-era US observatory")],
        country="US", state="California"),
    concept("vasco-project", "VASCO (Villarroel's Vanishing Stars Project)", "physics",
        [src(VID18, 439, "Transient-hunting project by Villarroel's team")],
        summary="Vanishing & Appearing Sources during a Century of Observations: Villarroel's project hunting stars that appear or vanish over historical timescales on astronomical plates."),
    event("july-27-1952-washington-flap", "Washington UFO Flap 1952", "other", "1952-07-27",
        [src(VID18, 441, "National Airport radar UFO sightings July 1952")],
        summary="July 1952 Washington DC UFO sightings: ghostlike objects darted across the CIA traffic control radar at National Airport for several hours; corroborated independently by Villarroel's Palomar transients on same dates."),
]
claims_18 = [
    ("villarroel-105k-pre-satellite-transients", 389,
     "Villarroel's team found ~105,000 unidentified transient light sources in northern-hemisphere Palomar plates — critically, from an era *before* Sputnik and any human-made orbital hardware.",
     "person-beatriz-villarroel", "on_record_statement",
     ["person-beatriz-villarroel", "location-palomar-observatory",
      "concept-vasco-project"],
     "Our original sample is around 105,000 transients from just the northern hemisphere. She detected these objects before the first satellite Sputnik ever orbited Earth."),
    ("july-1952-nine-objects-correlation", 437,
     "Two statistically-significant multi-transient events appear on Palomar plates: five objects in a narrow band on July 27 1952, and three super-bright 'stars' on July 19 1952 — both dates coincide with the Washington UFO flap.",
     "person-beatriz-villarroel", "on_record_statement",
     ["person-beatriz-villarroel", "event-july-27-1952-washington-flap",
      "person-enrique-solano"],
     "Five objects on a narrow band from the 27th of July 1952. Enrique Solano discovered another such example with three super bright beautiful stars from the 19th of July 1952."),
    ("bruehl-nuclear-correlation", 409,
     "Vanderbilt PhD Steven Bruehl correlated the transients with nuclear tests AND (smaller but statistically significant) with public UAP reports — expanding the nuclear-UAP connection into the astronomical record.",
     "person-jesse-michels", "cited_from_document",
     ["person-steven-bruehl", "person-beatriz-villarroel"],
     "We speak to a PhD from Vanderbilt, Dr. Steven Bruehl, who's followed up on Beatriz's study and correlates these UFO appearances with nuclear tests. The transients correlate not only with nuclear testing, but also show a small but statistically significant correlation with UAP reports."),
    ("reflective-flat-objects-mirrors", 379,
     "Villarroel describes the transients as 'short flashes not streaks' characteristic of objects that are extremely flat and extremely reflective — like mirrors.",
     "person-beatriz-villarroel", "on_record_statement",
     ["person-beatriz-villarroel"],
     "The short flashes and not streaks, they're associated with things that are extremely flat and extremely reflective. Like mirrors."),
    ("villarroel-peer-reviewed", 413,
     "All of Villarroel's transient work has received peer review in mainstream astronomical journals — academic validation of UFO-adjacent findings.",
     "person-jesse-michels", "on_record_statement",
     ["person-beatriz-villarroel"],
     "All of this work has received peer review in mainstream astronomical journals. She has finally caught the white whale in UFO science, academic validation."),
    ("villarroel-we-are-not-alone", 393,
     "Villarroel states on camera: 'If I look at everything that I learned in the last years, I will be fair — I don't think we are alone. I think we have company.'",
     "person-beatriz-villarroel", "personal_account",
     ["person-beatriz-villarroel", "concept-nhi"],
     "If I look at everything that I learned in the last years, I will be fair. I don't think we are alone. I think we have company."),
]

# ========== VIDEO 19: 2SQXAPCdmPE — Daniel Sheehan ==========
VID19 = "2SQXAPCdmPE"
entities_19 = [
    P("daniel-sheehan", "Daniel P. Sheehan", VID19, 456,
      "Attorney involved in every major American conspiracy",
      "American public-interest attorney; represented Elizondo, Greer, John Mack, Karen Silkwood; personally involved in Watergate; Church Committee files; UAP Disclosure Act advocacy.",
      ["Sheehan", "Shean"], "attorney",
      ["attorney", "public-interest", "advocate"]),
    P("mike-johnson-speaker", "Mike Johnson (Speaker)", VID19, 485,
      "US Speaker of the House; diluted Schumer UAP amendment",
      "US Speaker of the House; represents Dayton Ohio (Wright-Patterson district); Sheehan alleges his top aerospace-contractor donors drove dilution of Schumer's UAP Disclosure Act.",
      ["Speaker Johnson"], "politician",
      ["politician", "congress"]),
    P("bud-hopkins", "Bud Hopkins", VID19, 513,
      "Artist and investigator of abductee cases, childhood friend of John Mack",
      "American artist and investigator of UFO abduction cases; childhood friend of John Mack; referred abduction cases to Mack at Harvard.",
      ["Hopkins"], "artist / investigator",
      ["investigator", "researcher"]),
    P("ted-stevens", "Ted Stevens", VID19, 479,
      "US Senator from Alaska, secured AATIP funding with Reid",
      "US Senator from Alaska; co-secured $22M AATIP funding alongside Harry Reid.",
      ["Stevens"], "politician",
      ["politician", "senator", "historical"]),
    document("schumer-rounds-amendment", "Schumer-Rounds UAP Disclosure Amendment", "legislation",
        [src(VID19, 483, "Authorization-act amendment creating independent UAP disclosure review board")],
        summary="Senate Majority Leader Schumer and Senator Rounds' UAP Disclosure Act amendment to the NDAA — creating independent board of review for declassifying UAP material. Diluted in the House by Speaker Johnson."),
    program("mj-12-elite-group", "Majestic 12 (MJ-12)",
        [src(VID19, 319, "Elite panel of military/science/government UFO advisers")],
        summary="Alleged elite group of military, science, and government advisers governing the UFO issue since the late 1940s; described in MJ-12 document leaks in the 1980s-1990s.",
        acronym="MJ-12"),
]
claims_19 = [
    ("sheehan-represented-everyone", 459,
     "Sheehan represented UFO whistleblower Luis Elizondo, Stephen Greer, John Mack, and Karen Silkwood; he was also personally involved in the Watergate case.",
     "person-jesse-michels", "on_record_statement",
     ["person-daniel-sheehan", "person-luis-elizondo",
      "person-steven-greer", "person-john-mack"],
     "Represented UFO whistleblower Lou Elizondo, Harvard researcher John Mack and Karen Silkwood. Personally involved in the Watergate case."),
    ("aatip-22m-reid-stevens-inouye", 479,
     "AATIP was initially authorized under Senator Harry Reid with $22M, co-secured with Senator Ted Stevens of Alaska and Senator Inouye.",
     "person-daniel-sheehan", "personal_account",
     ["person-harry-reid", "person-ted-stevens", "program-aatip"],
     "Lou Elizondo was the program — it was actually under Senator Harry Reid, $22 million, Harry Reid, Ted Stevens from Alaska."),
    ("schumer-amendment-johnson-dilution", 485,
     "Sheehan alleges Mike Johnson, as House Speaker and representative of Wright-Patterson's district, diluted the Schumer UAP Disclosure amendment at the direction of top aerospace donors including Lockheed.",
     "person-daniel-sheehan", "speculation",
     ["person-daniel-sheehan", "person-mike-johnson-speaker",
      "document-schumer-rounds-amendment", "organization-lockheed-martin",
      "location-wright-patterson-afb"],
     "My understanding of the behind-the-scenes: he's the chair of this house intelligence but also represents Dayton Ohio which is where Wright Patterson — his top three donors are Lockheed."),
    ("skunkworks-patents-superluminal", 501,
     "Sheehan alleges Skunkworks / Lockheed are holding out on agreeing to a UAP disclosure law because they want patent rights on superluminal/anti-gravity technology.",
     "person-daniel-sheehan", "speculation",
     ["person-daniel-sheehan", "organization-skunkworks",
      "organization-lockheed-martin", "concept-reverse-engineering"],
     "They want to get patent rights to the for the next thousand years. For super luminal flight or anti-gravity stuff."),
    ("mack-represented-silkwood-similar", 513,
     "Sheehan represented John Mack at Harvard regarding the abduction research and at the pattern-evaluation phase of witness credibility assessment.",
     "person-daniel-sheehan", "personal_account",
     ["person-daniel-sheehan", "person-john-mack", "person-bud-hopkins"],
     "John Mack was the head through his friend Bud Hopkins. I represented him — he had worked with — was involved in vetting which ones weren't, what detailed information, several absolutely totally credible witnesses."),
    ("direct-face-to-face-underground-bases", 515,
     "Per Sheehan's witnesses: direct face-to-face contact with NHI has occurred in American underground military bases; beings communicate telepathically — e.g., speaking French to French interviewees.",
     "person-daniel-sheehan", "hearsay",
     ["person-daniel-sheehan", "phenomenon-alien-telepathy"],
     "Direct face-to-face contact with one or more of them in American Underground military bases. They telepathic — they talk French to French people."),
    ("sheehan-face-to-face-evidence-copious", 505,
     "Sheehan argues the evidence of face-to-face NHI contact across databases and witnesses is 'plain as day' — skeptic framing undercounts this body of testimony.",
     "person-daniel-sheehan", "on_record_statement",
     ["person-daniel-sheehan", "concept-nhi"],
     "Databases around this stuff — I actually think it's from another planet. People have been face to face with. For every one that says they're from Zeta they're also super deceptive."),
]

# ========== VIDEO 20: EzPmG_7WhXc — Jason Jorjani ==========
VID20 = "EzPmG_7WhXc"
entities_20 = [
    P("jason-jorjani", "Jason Jorjani", VID20, 551,
      "Philosopher, author of Prometheus and Atlas; UFO history and psychic warfare",
      "American philosopher; author of 'Prometheus and Atlas' and other works tracing UFO history, religious control systems, and psychic warfare.",
      ["Jorjani", "Georgiani", "Jason Reza Georgiani"], "philosopher",
      ["philosopher", "author"]),
    P("emanuel-kant", "Immanuel Kant", VID20, 587,
      "18th century German philosopher",
      "German philosopher; Jorjani notes Kant read Swedenborg's Arcana Coelestia in youth — relevant to interpreting his thing-in-itself framework.",
      ["Kant"], "philosopher",
      ["philosopher", "historical"]),
    P("emanuel-swedenborg", "Emanuel Swedenborg", VID20, 587,
      "Swedish polymath, mystic, scientist; Arcana Coelestia author",
      "Swedish scientist, theologian, and mystic (1688-1772); claimed spiritual communication with extraterrestrial inhabitants of planets; author of Arcana Coelestia.",
      ["Swedenborg"], "scientist / mystic",
      ["mystic", "historical"]),
    concept("religious-control-system", "Religious Control System", "politics",
        [src(VID20, 533, "Jorjani's framework: religion as imposed control by NHI")],
        summary="Jorjani's thesis: contemporary religions trace to NHI-imposed control structures — biblical-pattern deliveries of stone tablets and architectural blueprints being historical analogs of modern UAP-human interaction."),
    document("prometheus-and-atlas", "Prometheus and Atlas", "book",
        [src(VID20, 587, "Jorjani's first major book on tech/metaphysics")],
        summary="Jorjani's first book examining Kant and Descartes' shaping of enlightenment-era worldview, with emphasis on mediate knowledge and psi-abilities.",
        author="Jason Jorjani"),
    event("uto-battles-pre-renaissance", "Pre-Renaissance UFO Battles", "other", "1400-01-01",
        [src(VID20, 527, "Huge triangular craft and spheres over European cities")],
        summary="Pre-Renaissance historical accounts of massive UFO battles over European cities — triangular craft, spheres of various colors, some falling from the sky. Jorjani argues 'the bad guys won' in this rebellion."),
    event("carolingian-tyrants-of-air", "Carolingian 'Tyrants of the Air' Incident", "other", "0800-01-01",
        [src(VID20, 539, "Charlemagne contemplated war against sky tyrants after plague-spreading aerial ships")],
        summary="Carolingian-era account: three men and a woman descended from aerial ships near French fields; accused of spreading the plague by spraying doors with unknown substance. Charlemagne considered declaring war on the 'tyrants of the air'."),
]
claims_20 = [
    ("jorjani-religious-control-thesis", 529,
     "Jorjani's central thesis: religions are imposed control systems, evidenced by historical patterns of celestial beings delivering stone tablets (Moses pattern) and architectural blueprints.",
     "person-jason-jorjani", "on_record_statement",
     ["person-jason-jorjani", "concept-religious-control-system"],
     "In the struggle over reshaping human history, we wound up losing a rebellion against a control system that abides to this day. This thing is very similar to a thing that happened in our biblical records where a Lord presented Moses with a pattern to build a tabernacle."),
    ("pre-renaissance-ufo-battles", 527,
     "Jorjani cites historical records of massive UFO battles (triangular craft, coloured spheres) over European cities immediately before the Renaissance — reframed as 'the bad guys won.'",
     "person-jason-jorjani", "cited_from_document",
     ["person-jason-jorjani", "event-uto-battles-pre-renaissance"],
     "Immediately before the Renaissance, you had these huge UFO battles over various European cities. Huge triangular craft, spheres of various colors attacking each other."),
    ("black-plague-aerial-spraying", 537,
     "During the Black Plague outbreak, there are accounts of ships landing in fields; hooded figures walking door-to-door with 'spray cans' — plague outbreaks followed their visits.",
     "person-jason-jorjani", "cited_from_document",
     ["person-jason-jorjani", "event-carolingian-tyrants-of-air"],
     "At the time the black plague breaks out, there are many UFO sightings. Object land in fields. The plague broke out only after these people would land in the fields and they would go around with these hoods on and these spray cans."),
    ("ingo-swann-moon-remote-view", 549,
     "Ingo Swann was tasked to remote-view the moon; he saw tall Nordic people conducting slave labor on the moon.",
     "person-jason-jorjani", "cited_from_document",
     ["person-jason-jorjani", "person-ingo-swann"],
     "Ingo Swann is being tasked to remote view the moon. And here's what he saw there. He saw tall Nordic people conducting slave labor on the moon."),
    ("kant-swedenborg-extraterrestrials", 589,
     "Young Kant read Swedenborg's Arcana Coelestia which contains 'all kinds of accounts of extraterrestrials living on various planets and different gradations of existence' — Jorjani uses this to argue Kant's thing-in-itself is itself NHI-informed.",
     "person-jason-jorjani", "cited_from_document",
     ["person-jason-jorjani", "person-emanuel-kant", "person-emanuel-swedenborg",
      "document-prometheus-and-atlas"],
     "In Kant's own youth he actually took the time and care to read the entirety of Swedenborg's Arcana Coelestia the secrets of heaven which has all kinds of accounts of extraterrestrials living on various planets."),
    ("jorjani-bell-curve-nuts-bolts-vs-consciousness", 567,
     "Jorjani's meta-analysis: UFO discourse bell curve has three positions — normie-denier, middle-of-curve nuts-and-bolts, and end-of-curve consciousness-first — with a DOUBLE end at abstract metaphysics that ironically serves as a defense mechanism against disturbing tangible realities.",
     "person-jason-jorjani", "on_record_statement",
     ["person-jason-jorjani", "concept-nhi"],
     "I think that there's a place on the other side of the bell curve from where the normies are. You can wind up developing such an abstract meta-interpretation of these phenomena that you're actually occulting some more tangible aspects of it that are deeply disturbing."),
]

# ========== VIDEO 21: aGqFOxuYRT0 — Dennis Åsberg / Baltic USO ==========
VID21 = "aGqFOxuYRT0"
entities_21 = [
    P("dennis-asberg", "Dennis Åsberg", VID21, 601,
      "Swedish treasure hunter; discovered Baltic Sea USO",
      "Swedish treasure hunter; on 2011-06-19 discovered a 60m-wide circular object 90m below the Baltic Sea surface — now known as the Baltic Sea Anomaly.",
      ["Asberg", "Asber"], "treasure hunter",
      ["witness", "investigator"]),
    incident("2011-baltic-sea-anomaly", "Baltic Sea Anomaly (USO)", "sighting", "2011-06-19",
             [src(VID21, 603, "60m-wide object on Baltic seafloor with EM effects")],
             summary="Circular 60m-wide object discovered 90m below the Baltic Sea by Swedish treasure hunter Dennis Åsberg; breaks GPS, disables ROVs, emits gas/'milk'; struck by lightning; tracked by NATO ships. Not attached to seabed."),
    location("baltic-sea", "Baltic Sea", "region",
        [src(VID21, 607, "Remote section of the Baltic Sea where the anomaly was found")],
        country="SE"),
]
claims_21 = [
    ("asberg-60m-uso-discovery", 603,
     "On June 19 2011 Dennis Åsberg's Ocean X crew discovered a 60m-wide circular object with straight 90° corridors and flat walls sitting 90m below the Baltic Sea — it is not attached to the seabed (not natural geology).",
     "person-dennis-asberg", "personal_account",
     ["person-dennis-asberg", "incident-2011-baltic-sea-anomaly",
      "location-baltic-sea"],
     "It's round. And then we have these corridors. You have angles, 90 degree angles. It's not attached to the seabed floor. I have never seen anything like that before."),
    ("asberg-em-anomalies-rov-dead", 623,
     "Electromagnetic anomalies are rampant around the object — GPS fails, ROVs and drones stop working as they near it.",
     "person-dennis-asberg", "personal_account",
     ["person-dennis-asberg", "incident-2011-baltic-sea-anomaly"],
     "Electromagnetic anomalies are rampant around it. It breaks down GPS, subc rovers, drones. When we have used the ROV, the ROV stops working. We lost GPS very close to the object."),
    ("asberg-gas-emission-breathing", 637,
     "The object visibly emits a milky gas from a hole — Åsberg describes it as 'like breathing' — near-biological movement quality.",
     "person-dennis-asberg", "personal_account",
     ["person-dennis-asberg", "incident-2011-baltic-sea-anomaly"],
     "We have video of smoke coming out of the water above the object as if it's fuming or emitting gas. Almost like a biological organism."),
    ("asberg-struck-by-lightning", 657,
     "The Baltic anomaly was struck by lightning on-video — an extraordinarily unlikely natural coincidence for a discrete object under water.",
     "person-dennis-asberg", "personal_account",
     ["person-dennis-asberg", "incident-2011-baltic-sea-anomaly"],
     "It was literally struck by lightning, an occurrence often considered a high water mark for its unlikeliness."),
    ("asberg-nato-tracking", 657,
     "NATO ships encircled the Ocean X crew during their investigation; Åsberg confronted NATO headquarters in Stockholm with his footage and received no response.",
     "person-dennis-asberg", "personal_account",
     ["person-dennis-asberg", "incident-2011-baltic-sea-anomaly"],
     "We also have video of NATO ships encircling this object and tracking Dennis's Ocean X crew in the middle of the Baltic Sea. I have filmed you. So I know you have been there. Nothing. You don't say anything."),
]

# ========== VIDEO 22: A_LsUSxTm7A — Matt LaCroix / 12,000 BC ==========
VID22 = "A_LsUSxTm7A"
entities_22 = [
    P("matt-lacroix", "Matt LaCroix", VID22, 679,
      "Author and researcher of lost civilizations",
      "American researcher and author focused on lost ice-age civilizations; builds on Hancock's Younger-Dryas framework with specific civilization-identification research including Sphinx, Giza subterranean complexes, and Mesopotamian parallels.",
      ["LaCroix", "Matt lroy"], "researcher / author",
      ["researcher", "author"]),
    P("robert-schoch", "Robert Schoch", VID22, 691,
      "Boston University geologist; Sphinx water-erosion theorist",
      "Boston University geologist; established the Sphinx water-erosion thesis (vs. wind erosion) in 1991, forcing a re-dating of the Sphinx to the pre-dynastic era.",
      ["Schoch", "Dr. Robert Schoch"], "geologist",
      ["scientist", "geologist"]),
    P("john-anthony-west", "John Anthony West", VID22, 691,
      "Egyptologist who recruited Schoch to investigate the Sphinx enclosure",
      "Independent Egyptologist who in 1991 recruited Robert Schoch to investigate the Sphinx enclosure water-erosion hypothesis.",
      ["John A. West"], "egyptologist",
      ["researcher", "historical"]),
    P("edgar-cayce", "Edgar Cayce", VID22, 711,
      "American psychic who predicted the Halls of Amenti under the Sphinx",
      "Early-20th-century American psychic; predicted an 'ancient library' or Hall of Records beneath the Sphinx — the 'Halls of Amenti'.",
      ["Cayce"], "psychic / healer",
      ["historical", "psychic"]),
    concept("sphinx-water-erosion", "Sphinx Water Erosion Hypothesis", "physics",
        [src(VID22, 691, "Water-erosion pattern on the Sphinx enclosure")],
        summary="Robert Schoch's hypothesis that erosion on the Sphinx enclosure is water-caused rather than wind-caused — implying construction during a wet climatic period pushing the Sphinx's date back thousands of years to pre-dynastic Egypt."),
    location("giza-plateau", "Giza Plateau / Egypt", "region",
        [src(VID22, 675, "Sphinx, pyramids, and subterranean void complex")],
        country="EG"),
    concept("halls-of-amenti", "Halls of Amenti / Hall of Records", "metaphysics",
        [src(VID22, 711, "Alleged ancient library beneath the Sphinx")],
        summary="Alleged ancient library system beneath the Giza Sphinx, referenced by Edgar Cayce and supported by 1990s sonar/ground-penetrating-radar readings showing large voids with discrete objects."),
]
claims_22 = [
    ("schoch-sphinx-water-erosion", 693,
     "Robert Schoch established (1991 with John Anthony West) that the Sphinx enclosure shows water-erosion patterns inconsistent with dynastic-era dating — implying Sphinx construction during a wet climate ~10,500 BCE.",
     "person-matt-lacroix", "cited_from_document",
     ["person-matt-lacroix", "person-robert-schoch", "person-john-anthony-west",
      "concept-sphinx-water-erosion"],
     "Dr Robert Schoch is one of the main players that was brought over by John Anthony West to go investigate the Sphinx enclosure to see if it is truly wind erosion or whether or not it's really water erosion."),
    ("giza-subterranean-voids", 707,
     "1990s sonar/ground-penetrating-radar readings (led by Schoch's team) documented large subterranean voids with discrete cut objects beneath the Sphinx and Great Pyramids — four entrances identified on the Sphinx itself.",
     "person-matt-lacroix", "cited_from_document",
     ["person-matt-lacroix", "person-robert-schoch", "location-giza-plateau",
      "concept-halls-of-amenti"],
     "In the 90s they found these massive voids and it's not just under the Sphinx it's under the Great Pyramids as well. They all connect with these subterranean underworld type of areas. Four entrances under the Sphinx — one under the left paw, one on the top of the head."),
    ("egypt-ministry-drilling-misdirection", 721,
     "Per LaCroix: after the 1990s void findings became public, Egyptian authorities boarded over the Sphinx's paw entrance and conducted misleading drill-tests in locations that were NOT void locations — producing a 'no voids here' disinformation narrative.",
     "person-matt-lacroix", "speculation",
     ["person-matt-lacroix", "location-giza-plateau"],
     "The Egyptian authorities came through and they boarded up the front of the Paw with boards. They ended up drilling down to prove to the public that there was no voids but they purposely went where that wasn't entrances."),
    ("sphinx-head-disproportion-relion", 699,
     "LaCroix asserts the Sphinx's head is disproportionately small to its body because it was originally a lion (aligned with the 10,500 BCE Leo vernal equinox) — dynastic Egyptians later recarved the head into the pharaonic likeness.",
     "person-matt-lacroix", "speculation",
     ["person-matt-lacroix", "concept-sphinx-water-erosion"],
     "I believe 100% that if you look at the way the body of the Sphinx is versus the head, the head's too small. I believe as well it was a lion."),
    ("pink-granite-500-miles-silica", 735,
     "LaCroix notes pink granite found throughout the Giza Plateau was transported from 500 miles away (Aswan Quarry) — this silica-quartz specificity may be intentional because quartz has information-storage potential; proposes lost-tech encoded recording in stone.",
     "person-matt-lacroix", "speculation",
     ["person-matt-lacroix", "location-giza-plateau"],
     "All the pink granite we find throughout the Giza Plateau came from 500 miles away in the Aswan Quarry. That type of pink granite is extremely high in silica quartz — the same substance we use for watches. Is there something there with keeping recording messages?"),
    ("lacroix-atlantis-sealed-by-flood", 677,
     "LaCroix's framing: the Atlantis myth refers to the civilization whose subterranean cities at Giza were sealed and buried by the Younger-Dryas flood.",
     "person-matt-lacroix", "speculation",
     ["person-matt-lacroix", "concept-younger-dryas-impact",
      "concept-halls-of-amenti"],
     "It was sealed and buried and concealed by the flood. I think this is what we call Atlantis — I would say that it's what we're looking for, the lost civilizations."),
]


if __name__ == "__main__":
    print("Extending videos 13-22...")
    extend(VID13, entities_13, claims_13)
    extend(VID14, entities_14, claims_14)
    extend(VID15, entities_15, claims_15)
    extend(VID16, entities_16, claims_16)
    extend(VID17, entities_17, claims_17)
    extend(VID18, entities_18, claims_18)
    extend(VID19, entities_19, claims_19)
    extend(VID20, entities_20, claims_20)
    extend(VID21, entities_21, claims_21)
    extend(VID22, entities_22, claims_22)
    print("Done.")
